#!/bin/bash

IOX_PATH="/home/unmesh/iox_test/"
source ${IOX_PATH}"common"
LOGGER_PATH=${IOX_PATH}"dio/logger"
STS_PATH=${IOX_PATH}"dio/sts"
DIO_PROVISION_LOG=${IOX_PATH}"dio/dio_provision_log"

device_not_unprovisioned="Device not in UNPROVISIONED state"
sts_expected_state="provisioned"

test_num=1

subscribe_sts_event()
{
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/sts" > ${STS_PATH}
	pids+=($!)
}

dio_provision_test1()
{
	echo -n "dio_provision_test"${test_num} | tee -a ${RESULT_LOG} ${DIO_PROVISION_LOG}
	((test_num++)) 
	start_time=$(date | awk '{print $4}')	
	echo "" >> ${DIO_PROVISION_LOG}
	echo "START_TIME : "${start_time} >> ${DIO_PROVISION_LOG}
	subscribe_logger_event &
	mosquitto_pub -m '{"action":"provision","args":{"unid":"256"}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/do"
	echo "mosquitto_pub -m '{"action":"provision","args":{"unid":"256"}}' -t '"glp/0/17q2d9v/rq/dev/iox/dio/do"'" >> ${DIO_PROVISION_LOG}
	parse_logger "${device_not_unprovisioned}" ${DIO_PROVISION_LOG}
	result "logger"
	end_time=$(date | awk '{print $4}')
	echo "END_TIME : "${end_time} >> ${DIO_PROVISION_LOG}
	execution_time ${start_time} ${end_time}
	echo "" | tee -a ${RESULT_LOG} ${DIO_PROVISION_LOG}
	echo "==============================================================================" | tee -a ${DIO_PROVISION_LOG}
}

dio_provision_test2()
{
	echo -n "dio_provision_test"${test_num} | tee -a ${RESULT_LOG} ${DIO_PROVISION_LOG}
	((test_num++)) 
	start_time=$(date | awk '{print $4}')	
	echo "" >> ${DIO_PROVISION_LOG}
	echo "START_TIME : "${start_time} >> ${DIO_PROVISION_LOG}
	subscribe_logger_event &
	subscribe_sts_event &
	mosquitto_pub -m '{"action":"provision","args":{}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/do"
	echo "mosquitto_pub -m '{"action":"provision","args":{}}' -t '"glp/0/17q2d9v/rq/dev/iox/dio/do"'" >> ${DIO_PROVISION_LOG}
	parse_logger "${device_not_unprovisioned}" ${DIO_PROVISION_LOG}
	parse_sts "${sts_expected_state}" ${DIO_PROVISION_LOG}
	result "sts"
	end_time=$(date | awk '{print $4}')
	echo "END_TIME : "${end_time} >> ${DIO_PROVISION_LOG}
	execution_time ${start_time} ${end_time}
	echo "" | tee -a ${RESULT_LOG} ${DIO_PROVISION_LOG}
	echo "==============================================================================" | tee -a ${DIO_PROVISION_LOG}
}

dio_provision_test3()
{
	echo -n "dio_provision_test"${test_num} | tee -a ${RESULT_LOG} ${DIO_PROVISION_LOG}
	((test_num++)) 
	start_time=$(date | awk '{print $4}')	
	echo "" >> ${DIO_PROVISION_LOG}
	echo "START_TIME : "${start_time} >> ${DIO_PROVISION_LOG}
	subscribe_sts_event &
	mosquitto_pub -m '{"action":"provision","args":{"unid":"abcd"}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/do"
	echo "mosquitto_pub -m '{"action":"provision","args":{"unid":"abcd"}}' -t '"glp/0/17q2d9v/rq/dev/iox/dio/do"'" >> ${DIO_PROVISION_LOG}
	parse_sts "${sts_expected_state}" ${DIO_PROVISION_LOG}
	result "sts"
	end_time=$(date | awk '{print $4}')
	echo "END_TIME : "${end_time} >> ${DIO_PROVISION_LOG}
	execution_time ${start_time} ${end_time}
	echo "" | tee -a ${RESULT_LOG} ${DIO_PROVISION_LOG}
	echo "==============================================================================" | tee -a ${DIO_PROVISION_LOG}
}	

dio_provision_test4()
{
	echo -n "dio_provision_test"${test_num} | tee -a ${RESULT_LOG} ${DIO_PROVISION_LOG}
	((test_num++)) 
	start_time=$(date | awk '{print $4}')	
	echo "" >> ${DIO_PROVISION_LOG}
	echo "START_TIME : "${start_time} >> ${DIO_PROVISION_LOG}
	subscribe_sts_event &
	mosquitto_pub -m '{"action":"provision","args":{"unid":"256"}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/do"
	echo "mosquitto_pub -m '{"action":"provision","args":{"unid":"256"}}' -t '"glp/0/17q2d9v/rq/dev/iox/dio/do"'" >> ${DIO_PROVISION_LOG}
	parse_sts "${sts_expected_state}" ${DIO_PROVISION_LOG}
	result "sts"
	end_time=$(date | awk '{print $4}')
	echo "END_TIME : "${end_time} >> ${DIO_PROVISION_LOG}
	execution_time ${start_time} ${end_time}
	echo "" | tee -a ${RESULT_LOG} ${DIO_PROVISION_LOG}
	echo "==============================================================================" | tee -a ${DIO_PROVISION_LOG}
	
}

dio_provision_test5()
{
	echo -n "dio_provision_test"${test_num} | tee -a ${RESULT_LOG} ${DIO_PROVISION_LOG}
	((test_num++)) 
	start_time=$(date | awk '{print $4}')	
	echo "" >> ${DIO_PROVISION_LOG}
	echo "START_TIME : "${start_time} >> ${DIO_PROVISION_LOG}
	subscribe_logger_event &
	mosquitto_sub -t "glp/0/./=logger/event" > ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"provision","args":{"unid":"257"}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/do"
	echo "mosquitto_pub -m '{"action":"provision","args":{"unid":"257"}}' -t '"glp/0/17q2d9v/rq/dev/iox/dio/do"'" >> ${DIO_PROVISION_LOG}
	parse_logger "${device_not_unprovisioned}" ${DIO_PROVISION_LOG}
	result "logger"
	end_time=$(date | awk '{print $4}')
	echo "END_TIME : "${end_time} >> ${DIO_PROVISION_LOG}
	execution_time ${start_time} ${end_time}
	echo "" | tee -a ${RESULT_LOG} ${DIO_PROVISION_LOG}
	echo "==============================================================================" | tee -a ${DIO_PROVISION_LOG}
	
}

dio_provision_test6()
{
	echo -n "dio_provision_test"${test_num} | tee -a ${RESULT_LOG} ${DIO_PROVISION_LOG}
	((test_num++)) 
	start_time=$(date | awk '{print $4}')
	echo "" >> ${DIO_PROVISION_LOG}
	echo "START_TIME : "${start_time} >> ${DIO_PROVISION_LOG}
	subscribe_sts_event &
	mosquitto_pub -m '{"action":"provision"}' -t "glp/0/17q2d9v/rq/dev/iox/dio/do"
	echo "mosquitto_pub -m '{"action":"provision"}' -t '"glp/0/17q2d9v/rq/dev/iox/dio/do"'" >> ${DIO_PROVISION_LOG}
	parse_sts "${sts_expected_state}" ${DIO_PROVISION_LOG}
	result "sts"
	end_time=$(date | awk '{print $4}')
	echo "END_TIME : "${end_time} >> ${DIO_PROVISION_LOG}
	execution_time ${start_time} ${end_time}
	echo "" | tee -a ${RESULT_LOG} ${DIO_PROVISION_LOG}
	echo "==============================================================================" | tee -a ${DIO_PROVISION_LOG}
	
}

setup_time

dio_provision_test1
dio_provision_test2
dio_provision_test3
dio_provision_test4
dio_provision_test5
dio_provision_test6

kill_process
