#!/bin/bash

LOGGER_PATH="/home/unmesh/iox_test/dio/logger"
STS_PATH="/home/unmesh/iox_test/dio/sts"

kill_process()
{
    pkill mosquitto_sub
    if [[ $? -eq 0 ]];
    then
        echo "mosquitto_sub process killed"
    else
        echo "failed to kill mosquitto_sub process"
    fi
	rm ${LOGGER_PATH}
	rm ${STS_PATH}
}

parse_logger()
{
	sleep 5
	if [[ -s ${LOGGER_PATH} ]];
	then 
		out=$(grep 'utc' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 -B4 -A1 "regex" ${LOGGER_PATH})
		parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
		echo "parse : "${parse}
	fi
}

parse_sts()                                                                                       
{
    sleep 5
	if [[ -s ${STS_PATH} ]];
	then 
		out=$(grep 'mru' ${STS_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 -B11 -A1 "regex" ${STS_PATH})
		sleep 2
    	state=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["state"]')
    	echo "state : "${state}
	fi
}

dio_deprovision_test1()
{
	echo "test1 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"deprovision"}' -t "glp/0/17q2d9v/rq/dev/iox/dio/do"
	parse_logger
}

dio_deprovision_test2()
{
	echo "test2 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"deprovision"}' -t "glp/0/17q2d9v/rq/dev/iox/dio/do" 
	parse_logger
}

dio_deprovision_test3()
{
	echo "test3 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/sts" > ${STS_PATH} &
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"deprovision"}' -t "glp/0/17q2d9v/rq/dev/iox/dio/do"
	parse_logger
	parse_sts
}

dio_deprovision_test4()
{
	echo "test4 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"deprovision"}' -t "glp/0/17q2d9v/rq/dev/iox/dio/do"
	parse_logger
}

dio_deprovision_test1
dio_deprovision_test2
dio_deprovision_test3
dio_deprovision_test4

kill_process

