#!/bin/bash

source env_var.sh
source ${IOX_PATH}"/common.sh"
source ${IOX_PATH}"/iox.config"
source ${IOX_PATH}"/errors.sh"

LOG_EVENT_LOGGER=${IOX_PATH}"/dio/logger"
LOG_DIO_RESET=${IOX_PATH}"/dio/dio_reset_log"


test_num=1

dio_reset_test1()
{
	start_time=$(date | awk '{print $4}')
	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"reset"}' -t "glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/do"
	parse_logger "${err_reset_hndl}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"reset"}' -t '"glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/do"'")
	result_logs "dio_reset_test" ${test_num} ${LOG_DIO_RESET}  ${start_time} "${pub}"
}

setup_time

dio_reset_test1

kill_process
