#!/bin/bash

source env_var.sh
source ${IOX_PATH}"/common.sh"
source ${IOX_PATH}"/iox.config"
source ${IOX_PATH}"/errors.sh"

LOG_EVENT_LOGGER=${IOX_PATH}"/dio/logger"
LOG_STS=${IOX_PATH}"/dio/sts"
LOG_DIO_PROV=${IOX_PATH}"/dio/dio_provision_log"


test_num=1

subscribe_sts_event()
{
	mosquitto_sub -t "glp/0/${SID}/fb/dev/iox/${DIO_DEV_NAME}/sts" > ${LOG_STS}
}

dio_provision_test1()
{
	start_time=$(date | awk '{print $4}')	
	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"provision","args":{"unid":"256"}}' -t "glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/do"
	parse_logger "${device_not_unprovisioned}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"provision","args":{"unid":"256"}}' -t '"glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/do"'")
	result_logs "dio_provision_test" ${test_num} ${LOG_DIO_PROV}  ${start_time} "${pub}"
}

dio_provision_test2()
{
	start_time=$(date | awk '{print $4}')	
	subscribe_sts_event &
	pids+=($!)
	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"provision","args":{}}' -t "glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/do"
	parse_sts "${prov_expected_state}"
	parse_logger "${device_not_unprovisioned}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"provision","args":{}}' -t '"glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/do"'")
	result_logs "dio_provision_test" ${test_num} ${LOG_DIO_PROV}  ${start_time} "${pub}"
}

dio_provision_test3()
{
	start_time=$(date | awk '{print $4}')	
	subscribe_sts_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"provision","args":{"unid":"abcd"}}' -t "glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/do"
	parse_sts "${prov_expected_state}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"provision","args":{"unid":"abcd"}}' -t '"glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/do"'")
	result_logs "dio_provision_test" ${test_num} ${LOG_DIO_PROV}  ${start_time} "${pub}"
}	

dio_provision_test4()
{
	start_time=$(date | awk '{print $4}')	
	subscribe_sts_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"provision","args":{"unid":"256"}}' -t "glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/do"
	parse_sts "${prov_expected_state}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"provision","args":{"unid":"256"}}' -t '"glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/do"'")
	result_logs "dio_provision_test" ${test_num} ${LOG_DIO_PROV}  ${start_time} "${pub}"
}

dio_provision_test5()
{
	start_time=$(date | awk '{print $4}')	
	subscribe_logger_event &
	pids+=($!)
	mosquitto_sub -t "glp/0/./=logger/event" > ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"provision","args":{"unid":"257"}}' -t "glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/do"
	parse_logger "${device_not_unprovisioned}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"provision","args":{"unid":"257"}}' -t '"glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/do"'")
	result_logs "dio_provision_test" ${test_num} ${LOG_DIO_PROV}  ${start_time} "${pub}"
}

dio_provision_test6()
{
	start_time=$(date | awk '{print $4}')
	subscribe_sts_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"provision"}' -t "glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/do"
	parse_sts "${prov_expected_state}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"provision"}' -t '"glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/do"'")
	result_logs "dio_provision_test" ${test_num} ${LOG_DIO_PROV}  ${start_time} "${pub}"
}

setup_time

dio_provision_test1
dio_provision_test2
dio_provision_test3
dio_provision_test4
dio_provision_test5
dio_provision_test6

kill_process
