#!/bin/bash

source env_var.sh
source ${IOX_PATH}"/common.sh"
source ${IOX_PATH}"/iox.config"
source ${IOX_PATH}"/errors.sh"

LOG_EVENT_LOGGER=${IOX_PATH}"/dio/logger"
LOG_DIO_TEST=${IOX_PATH}"/dio/dio_test_log"


test_num=1

dio_test_test1()
{
	start_time=$(date | awk '{print $4}')
	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"test"}' -t "glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/do"
	parse_logger "${err_test_hndl}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"test"}' -t '"glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/do"'")
	result_logs "dio_test_test" ${test_num} ${LOG_DIO_TEST}  ${start_time} "${pub}"
}

dio_test_test2()
{
	start_time=$(date | awk '{print $4}')
	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"test"}' -t "glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/do"
	parse_logger "${err_test_hndl}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"test"}' -t '"glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/do"'")
}

dio_test_test3()
{
	start_time=$(date | awk '{print $4}')
	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"test"}' -t "glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/do"
	parse_logger "${err_test_hndl}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"test"}' -t '"glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/do"'")
}

dio_test_test4()
{
	start_time=$(date | awk '{print $4}')
	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"test"}' -t "glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/do"
	parse_logger "${err_test_hndl}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"test"}' -t '"glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/do"'")
}

setup_time

dio_test_test1
dio_test_test2
dio_test_test3
dio_test_test4

kill_process
