#!/bin/bash

source env_var.sh
source ${IOX_PATH}"/common.sh"
source ${IOX_PATH}"/iox.config"
source ${IOX_PATH}"/errors.sh"

LOG_EVENT_LOGGER=${IOX_PATH}"/dio/logger"
LOG_DIO_WINK=${IOX_PATH}"/dio/dio_wink_log"


dio_wink_test1()
{
	start_time=$(date | awk '{print $4}')
	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"wink"}' -t "glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/do"
	parse_logger "${err_wink_hndl}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"wink"}' -t '"glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/do"'")
	result_logs "dio_wink_test" ${LOG_DIO_WINK}  ${start_time} "${pub}"
}

setup_time

dio_wink_test1

kill_process
