#!/bin/bash

IOX_PATH="/home/unmesh/iox_test/"
source ${IOX_PATH}"common"
LOGGER_PATH=${IOX_PATH}"dio/logger"
STS_PATH=${IOX_PATH}"dio/sts"
DIO_WINK_LOG=${IOX_PATH}"dio/dio_wink_log"

test_num=1

err_wink_hndl="ERROR in iox_wink handle"

dio_wink_test1()
{
	echo -n "dio_wink_test"${test_num} | tee -a ${RESULT_LOG} ${DIO_WINK_LOG}
	((test_num++)) 
	start_time=$(date | awk '{print $4}')
	echo "" >> ${DIO_WINK_LOG}
	echo "START_TIME : "${start_time} >> ${DIO_WINK_LOG}
	subscribe_logger_event &
	mosquitto_pub -m '{"action":"wink"}' -t "glp/0/17q2d9v/rq/dev/iox/dio/do"
	echo "mosquitto_pub -m '{"action":"wink"}' -t '"glp/0/17q2d9v/rq/dev/iox/dio/do"'" >> ${DIO_WINK_LOG}
	parse_logger "${err_wink_hndl}" ${DIO_WINK_LOG}
	result "logger"
	end_time=$(date | awk '{print $4}')
	echo "END_TIME : "${end_time} >> ${DIO_WINK_LOG}
	execution_time ${start_time} ${end_time}
	echo "" | tee -a ${RESULT_LOG} ${DIO_WINK_LOG}
	echo "==============================================================================" | tee -a ${DIO_WINK_LOG}
}

setup_time

dio_wink_test1

kill_process
