#!/bin/bash 

source env_var.sh
source ${IOX_PATH}"/common.sh"
source ${IOX_PATH}"/iox.config"
source ${IOX_PATH}"/errors.sh"

LOG_EVENT_LOGGER=${IOX_PATH}"/dio/logger"
LOG_STS=${IOX_PATH}"/dio/sts"
LOG_DIO_CREATE=${IOX_PATH}"/dio/dio_create_log"

subscribe_sts_event()
{
	mosquitto_sub -t "glp/0/${SID}/fb/dev/${IOX_PROTOCOL}/${LOGICAL_ID}dio/sts" > ${LOG_STS} 
}

dio_create_test1()
{
	start_time=$(date | awk '{print $4}')
  	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"create"}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${LOGICAL_ID}dio/do"
	parse_logger "${err_parse_args}" 
	result "logger"
	pub=("mosquitto_pub -m '{"action":"create"}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${LOGICAL_ID}dio/do"'")
	result_logs "dio_create_test" ${LOG_DIO_CREATE}  ${start_time} "${pub}"
}

dio_create_test2()
{
	start_time=$(date | awk '{print $4}')
	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"create","args":{"type":"900001050304DD00"}}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${LOGICAL_ID}dio/do"
	parse_logger "${no_unid}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"create","args":{"type":"900001050304DD00"}}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${LOGICAL_ID}dio/do"'")
	result_logs "dio_create_test" ${LOG_DIO_CREATE}  ${start_time} "${pub}"
}

dio_create_test3()
{
	start_time=$(date | awk '{print $4}')
 	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"create","args":{"type":"900001050304DD00"}}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${LOGICAL_ID}dio/do"
	parse_logger "${no_unid}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"create","args":{"type":"900001050304DD00"}}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${LOGICAL_ID}dio/do"'")
	result_logs "dio_create_test" ${LOG_DIO_CREATE}  ${start_time} "${pub}"
}

dio_create_test4()
{
	start_time=$(date | awk '{print $4}')
 	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"create","args":{"type":"900001050304DD00"}}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${LOGICAL_ID}dio/do"
	parse_logger "${no_unid}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"create","args":{"type":"900001050304DD00"}}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${LOGICAL_ID}dio/do"'")
	result_logs "dio_create_test" ${LOG_DIO_CREATE}  ${start_time} "${pub}"
}

dio_create_test5()
{
	start_time=$(date | awk '{print $4}')
 	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"create","args":{"type":"900001050304DD00"}}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${LOGICAL_ID}dio/do"
	parse_logger "${no_unid}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"create","args":{"type":"900001050304DD00"}}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${LOGICAL_ID}dio/do"'")
	result_logs "dio_create_test" ${LOG_DIO_CREATE}  ${start_time} "${pub}"
}

dio_create_test6()
{
	start_time=$(date | awk '{print $4}')
 	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"create","args":{"type":"900001050304DD00","provision":true}}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${LOGICAL_ID}dio/do"
	parse_logger "${no_unid}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"create","args":{"type":"900001050304DD00","provision":true}}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${LOGICAL_ID}dio/do"'")
	result_logs "dio_create_test" ${LOG_DIO_CREATE}  ${start_time} "${pub}"
}

dio_create_test7()
{
	start_time=$(date | awk '{print $4}')
	subscribe_sts_event &
	pids+=($!)
  	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"create","args":{"type":"900001050304DD00","provision":false,"unid":"256"}}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${LOGICAL_ID}dio/do"
	parse_sts "${create_expected_state}"
	parse_logger "${no_unid}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"create","args":{"type":"900001050304DD00","provision":false,"unid":"256"}}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${LOGICAL_ID}dio/do"'")
	result_logs "dio_create_test" ${LOG_DIO_CREATE}  ${start_time} "${pub}"
}

dio_create_test8()
{
	start_time=$(date | awk '{print $4}')
 	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"create","args":{"type":"900001050304DD00","provision":true,"unid":"abcd"}}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${LOGICAL_ID}dio/do"
	parse_logger "${device_created}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"create","args":{"type":"900001050304DD00","provision":true,"unid":"abcd"}}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${LOGICAL_ID}dio/do"'")
	result_logs "dio_create_test" ${LOG_DIO_CREATE}  ${start_time} "${pub}"
}

dio_create_test9()
{
	start_time=$(date | awk '{print $4}')
 	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"create","args":{"type":"900001050304DD00","provision":"true","unid":"256"}}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${LOGICAL_ID}dio/do"
	parse_logger "${invalid_provision}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"create","args":{"type":"900001050304DD00","provision":"true","unid":"256"}}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${LOGICAL_ID}dio/do"'")
	result_logs "dio_create_test" ${LOG_DIO_CREATE} ${start_time} "${pub}"
}

setup_time
dio_create_test1
dio_create_test2
dio_create_test3
dio_create_test4
dio_create_test5
dio_create_test6
dio_create_test7

sleep 30
dio_create_test8
dio_create_test9

kill_process


