#!/bin/bash

IOX_PATH="/home/unmesh/iox_test/"
source ${IOX_PATH}"common"
LOGGER_PATH=${IOX_PATH}"dio/logger"
STS_PATH=${IOX_PATH}"dio/sts"
DIO_DEPROVISION_LOG=${IOX_PATH}"dio/dio_deprovision_log"

device_not_provisioned="Device not in PROVISIONED state"
sts_expected_state="unprovisioned"

test_num=1

subscribe_sts_event()
{
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/sts" > ${STS_PATH}
	pids+=($!)
}

dio_deprovision_test1()
{
	echo -n "dio_deprovision_test"${test_num} | tee -a ${RESULT_LOG} ${DIO_DEPROVISION_LOG}
	((test_num++)) 
	start_time=$(date | awk '{print $4}')
	echo "" >> ${DIO_DEPROVISION_LOG}
	echo "START_TIME : "${start_time} >> ${DIO_DEPROVISION_LOG}
 	subscribe_logger_event &
	mosquitto_pub -m '{"action":"deprovision"}' -t "glp/0/17q2d9v/rq/dev/iox/dio/do"
	echo "mosquitto_pub -m '{"action":"deprovision"}' -t '"glp/0/17q2d9v/rq/dev/iox/dio/do"'" >> ${DIO_DEPROVISION_LOG}
	parse_logger "${device_not_provisioned}" ${DIO_DEPROVISION_LOG}
	result "logger"
	end_time=$(date | awk '{print $4}')
	echo "END_TIME : "${end_time} >> ${DIO_DEPROVISION_LOG}
	execution_time ${start_time} ${end_time}
	echo "" | tee -a ${RESULT_LOG} ${DIO_DEPROVISION_LOG}
	echo "==============================================================================" | tee -a ${DIO_DEPROVISION_LOG}
}

dio_deprovision_test2()
{	
	echo -n "dio_deprovision_test"${test_num} | tee -a ${RESULT_LOG} ${DIO_DEPROVISION_LOG}
	((test_num++)) 
	start_time=$(date | awk '{print $4}')
	echo "" >> ${DIO_DEPROVISION_LOG}
	echo "START_TIME : "${start_time} >> ${DIO_DEPROVISION_LOG}
 	subscribe_logger_event &
	mosquitto_pub -m '{"action":"deprovision"}' -t "glp/0/17q2d9v/rq/dev/iox/dio/do" 
	echo "mosquitto_pub -m '{"action":"deprovision"}' -t '"glp/0/17q2d9v/rq/dev/iox/dio/do"'" >> ${DIO_DEPROVISION_LOG}
	parse_logger "${device_not_provisioned}" ${DIO_DEPROVISION_LOG}
	result "logger"
	end_time=$(date | awk '{print $4}')
	echo "END_TIME : "${end_time} >> ${DIO_DEPROVISION_LOG}
	execution_time ${start_time} ${end_time}
	echo "" | tee -a ${RESULT_LOG} ${DIO_DEPROVISION_LOG}
	echo "==============================================================================" | tee -a ${DIO_DEPROVISION_LOG}
}

dio_deprovision_test3()
{
	echo -n "dio_deprovision_test"${test_num} | tee -a ${RESULT_LOG} ${DIO_DEPROVISION_LOG}
	((test_num++)) 
	start_time=$(date | awk '{print $4}')
	echo "" >> ${DIO_DEPROVISION_LOG}
	echo "START_TIME : "${start_time} >> ${DIO_DEPROVISION_LOG}
 	subscribe_sts_event &
	mosquitto_pub -m '{"action":"deprovision"}' -t "glp/0/17q2d9v/rq/dev/iox/dio/do"
	echo "mosquitto_pub -m '{"action":"deprovision"}' -t '"glp/0/17q2d9v/rq/dev/iox/dio/do"'" >> ${DIO_DEPROVISION_LOG}
	parse_sts "${STS_EXPECTED_STATE}" ${DIO_DEPROVISION_LOG}
	result "sts"
	end_time=$(date | awk '{print $4}')
	echo "END_TIME : "${end_time} >> ${DIO_DEPROVISION_LOG}
	execution_time ${start_time} ${end_time}
	echo "" | tee -a ${RESULT_LOG} ${DIO_DEPROVISION_LOG}
	echo "==============================================================================" | tee -a ${DIO_DEPROVISION_LOG}
}

dio_deprovision_test4()
{
	echo -n "dio_deprovision_test"${test_num} | tee -a ${RESULT_LOG} ${DIO_DEPROVISION_LOG}
	((test_num++)) 
	start_time=$(date | awk '{print $4}')
	echo "" >> ${DIO_DEPROVISION_LOG}
	echo "START_TIME : "${start_time} >> ${DIO_DEPROVISION_LOG}
	subscribe_logger_event &
	mosquitto_pub -m '{"action":"deprovision"}' -t "glp/0/17q2d9v/rq/dev/iox/dio/do"
	echo "mosquitto_pub -m '{"action":"deprovision"}' -t '"glp/0/17q2d9v/rq/dev/iox/dio/do"'" >> ${DIO_DEPROVISION_LOG}
	parse_logger "${device_not_provisioned}" ${DIO_DEPROVISION_LOG}
	result "logger"
	end_time=$(date | awk '{print $4}')
	echo "END_TIME : "${end_time} >> ${DIO_DEPROVISION_LOG}
	execution_time ${start_time} ${end_time}
	echo "" | tee -a ${RESULT_LOG} ${DIO_DEPROVISION_LOG}
	echo "==============================================================================" | tee -a ${DIO_DEPROVISION_LOG}
}

setup_time

dio_deprovision_test1
dio_deprovision_test2
dio_deprovision_test3
dio_deprovision_test4

kill_process



