#!/bin/bash

source env_var.sh
source ${IOX_PATH}"/common.sh"
source ${IOX_PATH}"/iox.config"
source ${IOX_PATH}"/errors.sh"

LOG_EVENT_LOGGER=${IOX_PATH}"/meter/3phase/logger"
LOG_STS=${IOX_PATH}"/meter/3phase/sts"
LOG_3PHASE_CREATE=${IOX_PATH}"/meter/3phase/3phase_create_log"

phase_err_args="Error in parsing args data"
phase_no_unid="No unid provided"
phase_invalid_unid="Invalid unid string"
phase_wrong_prov="Wrong Provision value"
phase_unprov_state="unprovisioned"

subscribe_sts_event()
{
	mosquitto_sub -t "glp/0/${SID}/fb/dev/iox/dio/sts" > ${LOG_STS}
}

3phase_create_test1()
{
	start_time=$(date | awk '{print $4}')
  	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"create"}' -t "glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/do"
	parse_logger "${phase_err_args}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"create"}' -t '"glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/do"'")
	result_logs "3phase_create_test" ${LOG_3PHASE_CREATE}  ${start_time} "${pub}"
}

3phase_create_test2()
{
	start_time=$(date | awk '{print $4}')
  	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"create","args":{"type":"ABCDEFG"}}' -t "glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/do"
	parse_logger "${phase_no_unid}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"create","args":{"type":"ABCDEFG"}}' -t '"glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/do"'")
	result_logs "3phase_create_test" ${LOG_3PHASE_CREATE}  ${start_time} "${pub}"
}

3phase_create_test3()
{
	start_time=$(date | awk '{print $4}')
  	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"create","args":{"type":"meter"}}' -t "glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/do"
	parse_logger "${phase_no_unid}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"create","args":{"type":"meter"}}' -t '"glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/do"'")
	result_logs "3phase_create_test" ${LOG_3PHASE_CREATE}  ${start_time} "${pub}"
}

3phase_create_test4()
{
	start_time=$(date | awk '{print $4}')
  	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"create","args":{"type":"meter"}}' -t "glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/do"
	parse_logger "${phase_no_unid}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"create","args":{"type":"meter"}}' -t '"glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/do"'")
	result_logs "3phase_create_test" ${LOG_3PHASE_CREATE}  ${start_time} "${pub}"
}

3phase_create_test5()
{
	start_time=$(date | awk '{print $4}')
  	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"create","args":{"type":"ABCDEFG"}}' -t "glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/do"
	parse_logger "${phase_no_unid}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"create","args":{"type":"ABCDEFG"}}' -t '"glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/do"'")
	result_logs "3phase_create_test" ${LOG_3PHASE_CREATE}  ${start_time} "${pub}"
}

3phase_create_test6()
{
	start_time=$(date | awk '{print $4}')
  	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"create","args":{"type":"meter","provision":true}}' -t "glp/0/${SID}/rq/dev/iox/amik_1/do"
	parse_logger "${phase_no_unid}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"create","args":{"type":"meter","provision":true}}' -t '"glp/0/${SID}/rq/dev/iox/amik_1/do"'")
	result_logs "3phase_create_test" ${LOG_3PHASE_CREATE}  ${start_time} "${pub}"
}

3phase_create_test7()
{
	start_time=$(date | awk '{print $4}')
  	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"create","args":{"type":"meter","provision":true,"unid":"abcd"}}' -t "glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/do"
	parse_logger "${phase_invalid_unid}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"create","args":{"type":"meter","provision":true,"unid":"abcd"}}' -t '"glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/do"'")
	result_logs "3phase_create_test" ${LOG_3PHASE_CREATE}  ${start_time} "${pub}"
}

3phase_create_test8()
{
	start_time=$(date | awk '{print $4}')
  	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"create","args":{"type":"meter","provision":"true","unid":"257"}}' -t "glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/do"
	parse_logger "${phase_wrong_provision}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"create","args":{"type":"meter","provision":"true","unid":"257"}}' -t '"glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/do"'")
	result_logs "3phase_create_test" ${LOG_3PHASE_CREATE}  ${start_time} "${pub}"
}

3phase_create_test9()
{
	start_time=$(date | awk '{print $4}')
	subscibe_sts_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"create","args":{"unid":"257","type":"meter","provision":false}}' -t "glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/do"
	parse_sts "${phase_unprov_state}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"create","args":{"unid":"257","type":"meter","provision":false}}' -t '"glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/do"'")
	result_logs "3phase_create_test" ${LOG_3PHASE_CREATE}  ${start_time} "${pub}"
}

3phase_create_test10()
{
	start_time=$(date | awk '{print $4}')
	subscibe_sts_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"create","args":{"unid":"257","type":"meter","provision":true}}' -t "glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/do"
	parse_sts "${phase_unprov_state}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"create","args":{"unid":"257","type":"meter","provision":true}}' -t '"glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/do"'")
	result_logs "3phase_create_test" ${LOG_3PHASE_CREATE}  ${start_time} "${pub}"
}

setup_time

3phase_create_test1
3phase_create_test2
3phase_create_test3
3phase_create_test4
3phase_create_test5
3phase_create_test6
3phase_create_test7
3phase_create_test8
3phase_create_test9
3phase_create_test10

kill_process

