#!/bin/bash

LOGGER_PATH="/home/unmesh/iox_test/meter/3phase/logger"

kill_process()
{
	pkill mosquitto_sub
	if [[ $? -eq 0 ]];
	then
		echo "mosquitto_sub process killed"
	else
		echo "failed to kill mosquitto_sub process"
	fi
	rm ${LOGGER_PATH}
}

parse_logger()
{
	sleep 5
	if [[ -s ${LOGGER_PATH} ]];
	then 
		out=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${LOGGER_PATH})
		parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
		echo "parse : "${parse}
	fi
}


	
3phase_create_test1()
{
	echo "test1 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"create"}' -t "glp/0/17q2d9v/rq/dev/iox/meter/do"
	parse_logger
}

3phase_create_test2()
{
	echo "test2 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"create","args":{"type":"ABCDEFG"}}' -t "glp/0/17q2d9v/rq/dev/iox/meter/do"
	parse_logger
}

3phase_create_test3()
{
	echo "test3 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"create","args":{"type":"meter"}}' -t "glp/0/17q2d9v/rq/dev/iox/meter/do"
	parse_logger
}

3phase_create_test4()
{
	echo "test4 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"create","args":{"type":"meter"}}' -t "glp/0/17q2d9v/rq/dev/iox/meter/do"
	parse_logger
}

3phase_create_test5()
{
	echo "test5 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"create","args":{"type":"ABCDEFG"}}' -t "glp/0/17q2d9v/rq/dev/iox/meter/do"
	parse_logger
}

3phase_create_test6()
{
	echo "test6 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"create","args":{"type":"meter","provision":true}}' -t "glp/0/17q2d9v/rq/dev/iox/amik_1/do"
	parse_logger
}

3phase_create_test7()
{
	echo "test7 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"create","args":{"type":"meter","provision":true,"unid":"abcd"}}' -t "glp/0/17q2d9v/rq/dev/iox/meter/do"
	parse_logger
}

3phase_create_test8()
{
	echo "test8 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"create","args":{"type":"meter","provision":"true","unid":"257"}}' -t "glp/0/17q2d9v/rq/dev/iox/meter/do"
	parse_logger
}

3phase_create_test9()
{
	echo "test9 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"create","args":{"unid":"257","type":"meter","provision":false}}' -t "glp/0/17q2d9v/rq/dev/iox/meter/do"
	parse_logger
}

3phase_create_test10()
{
	echo "test10 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"create","args":{"unid":"257","type":"meter","provision":true}}' -t "glp/0/17q2d9v/rq/dev/iox/meter/do"
	parse_logger
}

3phase_create_test1
3phase_create_test2
3phase_create_test3
3phase_create_test4
3phase_create_test5
3phase_create_test6
3phase_create_test7
3phase_create_test8
3phase_create_test9
3phase_create_test10

kill_process
