#!/bin/bash

LOGGER_PATH="/home/unmesh/iox_test/meter/3phase/logger"

kill_process()
{
	pkill mosquitto_sub
	if [[ $? -eq 0 ]];
	then
		echo "mosquitto_sub process killed"
	else
		echo "failed to kill mosquitto_sub process"
	fi
	rm ${LOGGER_PATH}
}

parse_logger()
{
	sleep 5
	if [[ -s ${LOGGER_PATH} ]];
	then 
		out=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${LOGGER_PATH})
		parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
		echo "parse : "${parse}
	fi
}


3phase_deep_test1()
{
	echo "test1 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '30' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/dia/1/di-val/monitor/rate"
	parse_logger
}

3phase_deep_test2()
{
	echo "test2 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '30' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/di/1/di-vala/monitor/rate"
	parse_logger
}

3phase_deep_test3()
{
	echo "test3 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/meter/if/phase/0" &
	mosquitto_pub -m '{"monitor":{"rate":100}}' -t "glp/0/17q2d9v/rq/dev/iox/meter/if/phase/0/nvoVoltageRMS"
	parse_logger
}

3phase_deep_test4()
{
	echo "test4 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/meter/if/phase/0" &
	mosquitto_pub -m '{"rate":100}' -t "glp/0/17q2d9v/rq/dev/iox/meter/if/phase/0/nvoVoltageRMS/monitor"
	parse_logger
}

3phase_deep_test5()
{
	echo "test5 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/meter/if/phase/0" &
	mosquitto_pub -m '20' -t "glp/0/17q2d9v/rq/dev/iox/meter/if/phase/0/nvoVoltageRMS/monitor/rate"
	parse_logger
}

3phase_deep_test1
3phase_deep_test2
3phase_deep_test3
3phase_deep_test4
3phase_deep_test5

kill_process
