#!/bin/bash

source env_var.sh
source ${IOX_PATH}"/common.sh"
source ${IOX_PATH}"/iox.config"
source ${IOX_PATH}"/errors.sh"

LOG_EVENT_LOGGER=${IOX_PATH}"/meter/3phase/logger"
LOG_STS=${IOX_PATH}"/meter/3phase/sts"
LOG_3PHASE_PROVISION=${IOX_PATH}"/meter/3phase/3phase_prov_log"
DIO_UNID="${IOX_INSTALL_ID}.dio"
METER_UNID="${IOX_INSTALL_ID}.meter"

phase_already_prov="Device is already in PROVISION STATE"
phase_prov_state="provisioned"

subscribe_sts_event()
{
	 mosquitto_sub -t "glp/0/${SID}/fb/dev/${IOX_PROTOCOL}/${METER_DEV_NAME}/sts" > ${STS_PATH} 
}

3phase_provision_test1()
{
	start_time=$(date | awk '{print $4}')
  	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"provision","args":{"unid":'"${DIO_UNID}"'}}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${METER_DEV_NAME}/do"
	parse_logger "${phase_already_prov}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"provision","args":{"unid":'"${DIO_UNID}"'}}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${METER_DEV_NAME}/do"'")
	result_logs "3phase_provision_test" ${LOG_3PHASE_PROVISION}  ${start_time} "${pub}"
}

3phase_provision_test2()
{
	start_time=$(date | awk '{print $4}')
	subscribe_sts_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"provision","args":{}}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${METER_DEV_NAME}/do"
	parse_sts "${phase_prov_state}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"provision","args":{}}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${METER_DEV_NAME}/do"'")
	result_logs "3phase_provision_test" ${LOG_3PHASE_PROVISION}  ${start_time} "${pub}"
}

3phase_provision_test3()
{
	start_time=$(date | awk '{print $4}')
	subscribe_sts_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"provision","args":{"unid":"abcd"}}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${METER_DEV_NAME}/do"
	parse_sts "${phase_prov_state}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"provision","args":{"unid":"abcd"}}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${METER_DEV_NAME}/do"'")
	result_logs "3phase_provision_test" ${LOG_3PHASE_PROVISION}  ${start_time} "${pub}"
}

3phase_provision_test4()
{
	start_time=$(date | awk '{print $4}')
	subscribe_sts_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"provision"}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${METER_DEV_NAME}/do"
	parse_sts "${phase_prov_state}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"provision"}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${METER_DEV_NAME}/do"'")
	result_logs "3phase_provision_test" ${LOG_3PHASE_PROVISION}  ${start_time} "${pub}"
}

3phase_provision_test5()
{
	start_time=$(date | awk '{print $4}')
	subscribe_sts_event &
	pids+=($!)
  	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"provision","args":{"unid":'"${METER_UNID}"'}}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${METER_DEV_NAME}/do"
	parse_sts "${phase_prov_state}"
	parse_logger "${phase_already_prov}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"provision","args":{"unid":'"${METER_UNID}"'}}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${METER_DEV_NAME}/do"'")
	result_logs "3phase_provision_test" ${LOG_3PHASE_PROVISION}  ${start_time} "${pub}"
}

3phase_provision_test6()
{
	start_time=$(date | awk '{print $4}')
	subscribe_sts_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"provision"}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${METER_DEV_NAME}/do"
	parse_sts "${phase_prov_state}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"provision"}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${METER_DEV_NAME}/do"'")
	result_logs "3phase_provision_test" ${LOG_3PHASE_PROVISION}  ${start_time} "${pub}"
}

3phase_provision_test7()
{
	start_time=$(date | awk '{print $4}')
  	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"provision"}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${METER_DEV_NAME}/do"
	parse_logger "${phase_already_prov}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"provision"}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${METER_DEV_NAME}/do"'")
	result_logs "3phase_provision_test" ${LOG_3PHASE_PROVISION}  ${start_time} "${pub}"
}

setup_time

3phase_provision_test1
3phase_provision_test2
3phase_provision_test3
3phase_provision_test4
3phase_provision_test5
3phase_provision_test6
3phase_provision_test7

kill_process

