#!/bin/bash

LOGGER_PATH="/home/unmesh/iox_test/meter/3phase/logger"
STS_PATH="/home/unmesh/iox_test/meter/3phase/sts"

kill_process()
{
	pkill mosquitto_sub 
	if [[ $? -eq 1 ]];
	then
		echo "failed to kill mosquitto_sub process"
	fi
}

parse_logger()
{
	sleep 5
	if [[ -s ${LOGGER_PATH} ]];
	then 
		out=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${LOGGER_PATH})
		out_time=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | awk '{print $2}')
		if [[ ${last_out_time} == ${out_time} ]];
		then
			echo "NO NEW MESSAGE FROM LOGGER"
		else
			parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
			if [[ ${parse} == ${1} ]];
			then
				LOGGER_RESULT="PASS"
			else
				LOGGER_RESULT="FAIL"
			fi
			last_out_time=${out_time}
		fi
	fi
	rm ${LOGGER_PATH}
}

parse_sts()
{
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/sts" > ${STS_PATH} &
	sleep 5
	if [[ -s ${STS_PATH} ]];
	then 
		out=$(awk -F "," '/mru/{print $NF}' ${STS_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${STS_PATH})
		sleep 2
		state=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["state"]')
		if [[ ${state} == "unprovisioned" ]];
		then
			STS_RESULT="PASS"
		else
			STS_RESULT="FAIL"
		fi
	fi
	rm ${STS_PATH}
}

subscribe_logger_event()
{
    mosquitto_sub -t "glp/0/./=logger/event" > ${LOGGER_PATH}
}

subscribe_sts_event()
{
	 mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/meter/sts" > ${STS_PATH} 
}


3phase_deprovision_test1()
{
	subscribe_logger_event &
	mosquitto_pub -m '{"action":"deprovision"}' -t "glp/0/17q2d9v/rq/dev/iox/meter/do"
	parse_logger
}

3phase_deprovision_test2()
{
	subscribe_logger_event &
	mosquitto_pub -m '{"action":"deprovision"}' -t "glp/0/17q2d9v/rq/dev/iox/meter/do"
	parse_logger
}

3phase_deprovision_test3()
{
	subscribe_logger_event &
	subscribe_sts_event &
	mosquitto_pub -m '{"action":"deprovision"}' -t "glp/0/17q2d9v/rq/dev/iox/meter/do"
	parse_logger
	parse_sts
}

3phase_deprovision_test4()
{
	subscribe_logger_event &
	mosquitto_pub -m '{"action":"deprovision"}' -t "glp/0/17q2d9v/rq/dev/iox/meter/do"
	parse_logger
}

3phase_deprovision_test5()
{
	subscribe_logger_event &
	mosquitto_pub -m '{"action":"deprovision"}' -t "glp/0/17q2d9v/rq/dev/iox/meter/do"
	parse_logger
}

3phase_deprovision_test1
3phase_deprovision_test2
3phase_deprovision_test3
3phase_deprovision_test4
3phase_deprovision_test5

kill_process

