#!/bin/bash

source env_var.sh
source ${IOX_PATH}"/common.sh"
source ${IOX_PATH}"/iox.config"
source ${IOX_PATH}"/errors.sh"

LOG_EVENT_LOGGER=${IOX_PATH}"/meter/3phase/logger"
LOG_STS=${IOX_PATH}"/meter/3phase/sts"
LOG_3PHASE_TEST=${IOX_PATH}"/meter/3phase/3phase_test_log"

err_iox_test_hndl="ERROR in iox_test handle"

3phase_test_test1()
{
	start_time=$(date | awk '{print $4}')
  	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"test"}' -t "glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/do"
	parse_logger "${err_iox_test_hndl}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"test"}' -t '"glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/do"'")
	result_logs "3phase_test_test" ${LOG_3PHASE_TEST}  ${start_time} "${pub}"
}

3phase_test_test2()
{
	start_time=$(date | awk '{print $4}')
  	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"test"}' -t "glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/do"
	parse_logger "${err_iox_test_hndl}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"test"}' -t '"glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/do"'")
	result_logs "3phase_test_test" ${LOG_3PHASE_TEST}  ${start_time} "${pub}"
}

3phase_test_test3()
{
	start_time=$(date | awk '{print $4}')
  	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"test"}' -t "glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/do"
	parse_logger "${err_iox_test_hndl}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"test"}' -t '"glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/do"'")
	result_logs "3phase_test_test" ${LOG_3PHASE_TEST}  ${start_time} "${pub}"
}

3phase_test_test4()
{
	start_time=$(date | awk '{print $4}')
  	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"test"}' -t "glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/do"
	parse_logger "${err_iox_test_hndl}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"test"}' -t '"glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/do"'")
	result_logs "3phase_test_test" ${LOG_3PHASE_TEST}  ${start_time} "${pub}"
}

3phase_test_test5()
{
	start_time=$(date | awk '{print $4}')
  	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"test"}' -t "glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/do"
	parse_logger "${err_iox_test_hndl}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"test"}' -t '"glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/do"'")
	result_logs "3phase_test_test" ${LOG_3PHASE_TEST}  ${start_time} "${pub}"
}

setup_time

3phase_test_test1
3phase_test_test2
3phase_test_test3
3phase_test_test4
3phase_test_test5

kill_process

