#!/bin/bash

LOGGER_PATH="/home/unmesh/iox_test/meter/3phase/logger"
STS_PATH="/home/unmesh/iox_test/meter/3phase/sts"

kill_process()
{
	pkill mosquitto_sub
	if [[ $? -eq 0 ]];
	then
		echo "mosquitto_sub process killed"
	else
		echo "failed to kill mosquitto_sub process"
	fi
	rm ${LOGGER_PATH}
	rm ${STS_PATH}
}

parse_logger()
{
	sleep 5
	if [[ -s ${LOGGER_PATH} ]];
	then 
		out=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${LOGGER_PATH})
		parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
		echo "parse : "${parse}
	fi
}

parse_sts()
{
	sleep 5
	if [[ -s ${STS_PATH} ]];
	then 
		out=$(awk -F "," '/mru/{print $NF}' ${STS_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${STS_PATH})
		sleep 2
		state=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["state"]')
		echo "state : "${state}
	fi
}



3phase_delete_test1()
{
	echo "test1 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/meter/sts" > ${STS_PATH} &
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"delete"}' -t "glp/0/17q2d9v/rq/dev/iox.411b19/meter/do"
	parse_logger
	parse_sts
}

3phase_delete_test2()
{
	echo "test2 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/meter/sts" > ${STS_PATH} &
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"delete"}' -t "glp/0/17q2d9v/rq/dev/iox.411b19/meter/do"
	parse_logger
	parse_sts
}

3phase_delete_test3()
{
	echo "test3 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/meter/sts" > ${STS_PATH} &
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"delete"}' -t "glp/0/17q2d9v/rq/dev/iox.411b19/meter/do"
	parse_logger
	parse_sts
}

3phase_delete_test4()
{
	echo "test4 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/meter/sts" > ${STS_PATH} &
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"delete"}' -t "glp/0/17q2d9v/rq/dev/iox.411b19/meter/do"
	parse_logger
	parse_sts
}

3phase_delete_test5()
{
	echo "test5 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/meter/sts" > ${STS_PATH} &
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"delete"}' -t "glp/0/17q2d9v/rq/dev/iox.411b19/meter/do"
	parse_logger
	parse_sts
}

3phase_delete_test1
3phase_delete_test2
3phase_delete_test3
3phase_delete_test4
3phase_delete_test5

kill_process
