#!/bin/bash

source env_var.sh
source ${IOX_PATH}"/common.sh"
source ${IOX_PATH}"/iox.config"
source ${IOX_PATH}"/errors.sh"

LOG_EVENT_LOGGER=${IOX_PATH}"/meter/3phase/logger"
LOG_STS=${IOX_PATH}"/meter/3phase/sts"
LOG_3PHASE_DEL=${IOX_PATH}"/meter/3phase/3phase_create_log"

phase_wo_timestamp="Deleted item without MRU timestamp"
phase_del_state="deleted"

subscribe_sts_event()
{
	 mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/${METER_DEV_NAME}/sts" > ${STS_PATH} 
}

3phase_delete_test1()
{
	start_time=$(date | awk '{print $4}')
	subscribe_sts_event &
	pids+=($!)
	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"delete"}' -t "glp/0/17q2d9v/rq/dev/iox/${METER_DEV_NAME}/do"
	parse_sts "${phase_wo_timestamp}"
	parse_logger "${phase_del_state}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"delete"}' -t '"glp/0/17q2d9v/rq/dev/iox/${METER_DEV_NAME}/do"'")
	result_logs "3phase_delete_test" ${LOG_3PHASE_DEL}  ${start_time} "${pub}"
}

3phase_delete_test2()
{
	start_time=$(date | awk '{print $4}')
	subscribe_sts_event &
	pids+=($!)
	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"delete"}' -t "glp/0/17q2d9v/rq/dev/iox/${METER_DEV_NAME}/do"
	parse_sts "${phase_wo_timestamp}"
	parse_logger "${phase_del_state}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"delete"}' -t '"glp/0/17q2d9v/rq/dev/iox/${METER_DEV_NAME}/do"'")
	result_logs "3phase_delete_test" ${LOG_3PHASE_DEL}  ${start_time} "${pub}"
}

3phase_delete_test3()
{
	start_time=$(date | awk '{print $4}')
	subscribe_sts_event &
	pids+=($!)
	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"delete"}' -t "glp/0/17q2d9v/rq/dev/iox/${METER_DEV_NAME}/do"
	parse_sts "${phase_wo_timestamp}"
	parse_logger "${phase_del_state}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"delete"}' -t '"glp/0/17q2d9v/rq/dev/iox/${METER_DEV_NAME}/do"'")
	result_logs "3phase_delete_test" ${LOG_3PHASE_DEL}  ${start_time} "${pub}"
}

3phase_delete_test4()
{
	start_time=$(date | awk '{print $4}')
	subscribe_sts_event &
	pids+=($!)
	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"delete"}' -t "glp/0/17q2d9v/rq/dev/iox/${METER_DEV_NAME}/do"
	parse_sts "${phase_wo_timestamp}"
	parse_logger "${phase_del_state}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"delete"}' -t '"glp/0/17q2d9v/rq/dev/iox/${METER_DEV_NAME}/do"'")
	result_logs "3phase_delete_test" ${LOG_3PHASE_DEL}  ${start_time} "${pub}"
}

3phase_delete_test5()
{
	start_time=$(date | awk '{print $4}')
	subscribe_sts_event &
	pids+=($!)
	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"delete"}' -t "glp/0/17q2d9v/rq/dev/iox/${METER_DEV_NAME}/do"
	parse_sts "${phase_wo_timestamp}"
	parse_logger "${phase_del_state}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"delete"}' -t '"glp/0/17q2d9v/rq/dev/iox/${METER_DEV_NAME}/do"'")
	result_logs "3phase_delete_test" ${LOG_3PHASE_DEL}  ${start_time} "${pub}"
}

setup_time

3phase_delete_test1
3phase_delete_test2
3phase_delete_test3
3phase_delete_test4
3phase_delete_test5

kill_process

