#!/bin/bash

kill_process()
{
	pkill mosquitto_sub
	if [[ $? -eq 0 ]];
	then
		echo "mosquitto_sub process killed"
	else
		echo "failed to kill mosquitto_sub process"
	fi
}

3phase_get_test1()
{
	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox/meter/if/phase/0/nvoPhaseFrequency"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"
}

3phase_get_test2()
{
	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox/meter/if/phase/0/nvoPhaseFrequency"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"
}

3phase_get_test3()
{
	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox/meterasd/if/phase/0/nvoPhaseFrequency"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"
}

3phase_get_test4()
{
	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox/meter/if/phase/10/nvoPhaseFrequency"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"
}

3phase_get_test5()
{
	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox/meter/if/phase/0/nvoPhaseFrequency_test"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"
}

3phase_get_test6()
{
	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox/meter/if/phase/0/nvoPhaseFrequency","dev/iox/meter/if/phase/0/nvoVoltageRMS"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"
}

3phase_get_test1
3phase_get_test2	
3phase_get_test3
3phase_get_test4
3phase_get_test5
3phase_get_test6

kill_process
