#!/bin/bash

LOGGER_PATH="/home/unmesh/iox_test/modbus/logger"
STS_PATH="/home/unmesh/iox_test/modbus/sts"

kill_process()
{
	pkill mosquitto_sub
	if [[ $? -eq 0 ]];
	then
		echo "mosquitto_sub process killed"
	else
		echo "failed to kill mosquitto_sub process"
	fi
	rm ${LOGGER_PATH}
	rm ${STS_PATH}
}

parse_logger()
{
	sleep 5
	if [[ -s ${LOGGER_PATH} ]];
	then 
		out=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${LOGGER_PATH})
		parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
		echo "parse : "${parse}
	fi
}

parse_sts()
{
	sleep 5
	if [[ -s ${STS_PATH} ]];
	then 
		out=$(awk -F "," '/mru/{print $NF}' ${STS_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${STS_PATH})
		sleep 2
		state=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["state"]')
		echo "state : "${state}
	fi
}

modbus_create_test1()
{
	echo "test1 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"create"}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
	parse_logger
}


modbus_create_test3()
{
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/cfg" &
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/sts" > ${STS_PATH} &
	mosquitto_pub -m '{"action":"create","args":{"type":"900014150040DB00"}}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
	parse_sts
}

modbus_create_test4()
{
	echo "test4 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"create","args":{"type":"900014150040DB00"}}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
	parse_logger
}

modbus_create_test5()
{
	echo "test5 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"create","args":{"type":"900000000000DB00"}}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
	parse_logger
}

modbus_create_test6()
{
	echo "test6 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"create","args":{"type":"900014150040DB00"}}' -t "glp/0/17q2d9v/rq/dev/iox/new_device.0/do"
	parse_logger
}

modbus_create_test7()
{
	echo "test7 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"create","args":{"type":"900014150040DB00","provision":"true"}}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
	parse_logger
}

modbus_create_test8()
{
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/cfg" &
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/sts" > ${STS_PATH} &
	mosquitto_pub -m '{"action":"create","args":{"type":"900014150040DB00","provision":"false","unid":"01:43"}}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
	parse_sts
}

modbus_create_test9()
{
	echo "test9 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"create","args":{"type":"900014150040DB00","provision":"true","unid":"abcd"}}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
	parse_logger
}

modbus_create_test10()
{
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/cfg" &
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/sts" > ${STS_PATH} &
	mosquitto_sub -t "glp/0/17q2d9v/fb/res/type/blk.900014150040DB00/0" &
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/if/block/0" &
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/sts" > ${STS_PATH} &
	mosquitto_pub -m '{"action":"create","args":{"type":"900014150040DB00","provision":"true","unid":"01:1"}}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
	parse_sts
}

modbus_create_test1
#modbus_create_test2
modbus_create_test3
modbus_create_test4
modbus_create_test5
modbus_create_test6
modbus_create_test7
modbus_create_test8
modbus_create_test9
modbus_create_test10

kill_process
