#!/bin/bash

LOGGER_PATH="/home/unmesh/iox_test/modbus/logger"
STS_PATH="/home/unmesh/iox_test/modbus/sts"

kill_process()
{
	pkill mosquitto_sub
	if [[ $? -eq 0 ]];
	then
		echo "mosquitto_sub process killed"
	else
		echo "failed to kill mosquitto_sub process"
	fi
	rm ${LOGGER_PATH}
	rm ${STS_PATH}
}

parse_logger()
{
	sleep 5
	if [[ -s ${LOGGER_PATH} ]];
	then 
		out=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${LOGGER_PATH})
		parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
		echo "parse : "${parse}
	fi
}

parse_sts()
{
	sleep 5
	if [[ -s ${STS_PATH} ]];
	then 
		out=$(awk -F "," '/mru/{print $NF}' ${STS_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${STS_PATH})
		sleep 2
		state=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["state"]')
		echo "state : "${state}
	fi
}


modbus_provision_test1()
{
	echo "test1 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"provision","args":{"unid":"01:1"}}' -t "glp/0/17q3jbh/rq/dev/iox/pm820/do"
	parse_logger
}

modbus_provision_test2()
{
	echo "test2 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"provision","args":{}}' -t "glp/0/17q3jbh/rq/dev/iox/pm820/do"
	parse_logger
}

modbus_provision_test3()
{
	echo "test3 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"provision","args":{"unid":"3000"}}' -t "glp/0/17q3jbh/rq/dev/iox/pm820/do"
	parse_logger
}

modbus_provision_test4()
{
	echo "test4 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"provision","args":{"unid":"01:1"}}' -t "glp/0/17q3jbh/rq/dev/iox/pm820/do"
	parse_logger
}

modbus_provision_test5()
{
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/sts" > ${STS_PATH} &
	mosquitto_pub -m '{"action":"provision","args":{"unid":"01:1"}}' -t "glp/0/17q3jbh/rq/dev/iox/pm820/do"
	parse_sts
}

modbus_provision_test6()
{
	echo "test6 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"provision","args":{"unid":"01:3"}}' -t "glp/0/17q3jbh/rq/dev/iox/pm820/do"
	parse_logger
}

modbus_provision_test7()
{
	echo "test7 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"provision"}' -t "glp/0/17q3jbh/rq/dev/iox/pm820/do"
	parse_logger
}

modbus_provision_test8()
{
	echo "test8 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"action":"provision","args":{"unid":"17"}}' -t "glp/0/17q3jbh/rq/dev/iox/pm820/do"
	parse_logger
}

modbus_provision_test1
modbus_provision_test2
modbus_provision_test3
modbus_provision_test4
modbus_provision_test5
modbus_provision_test6
modbus_provision_test7
modbus_provision_test8

kill_process
