#!/bin/bash

source env_var.sh
source ${IOX_PATH}"/common.sh"
source ${IOX_PATH}"/iox.config"
source ${IOX_PATH}"/errors.sh"

LOG_EVENT_LOGGER=${IOX_PATH}"/modbus/logger"
LOG_STS=${IOX_PATH}"/modbus/sts"
LOG_MODBUS_PROV=${IOX_PATH}"/modbus/modbus_prov_log"

subscribe_sts_event()
{
	 mosquitto_sub -t "glp/0/${SID}/fb/dev/${IOX_PROTOCOL}/pm820/sts" > ${STS_PATH} 
}

modbus_provision_test1()
{
	start_time=$(date | awk '{print $4}')
	subscribe_logger_event & 
	pids+=($!)
	mosquitto_pub -m '{"action":"provision","args":{"unid":"01:1"}}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/pm820/do"
	parse_logger "${DEV_NOT_FOUND}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"provision","args":{"unid":"01:1"}}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/pm820/do"'")
	result_logs "modbus_provision_test" ${LOG_MODBUS_PROV}  ${start_time} "${pub}"
}

modbus_provision_test2()
{
	start_time=$(date | awk '{print $4}') 
	subscribe_logger_event &  
	pids+=($!)
	mosquitto_pub -m '{"action":"provision","args":{}}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/pm820/do"
	parse_logger "${PROV_UNID_MISSING}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"provision","args":{}}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/pm820/do"'")
	result_logs "modbus_provision_test" ${LOG_MODBUS_PROV}  ${start_time} "${pub}"
}

modbus_provision_test3()
{
	start_time=$(date | awk '{print $4}')  
	subscribe_logger_event &  
	pids+=($!)
	mosquitto_pub -m '{"action":"provision","args":{"unid":"3000"}}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/pm820/do"
	parse_logger "${INVALID_UNID}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"provision","args":{"unid":"3000"}}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/pm820/do"'")
	result_logs "modbus_provision_test" ${LOG_MODBUS_PROV}  ${start_time} "${pub}"
}

modbus_provision_test4()
{
	start_time=$(date | awk '{print $4}')  
	subscribe_logger_event &  
	pids+=($!)
	mosquitto_pub -m '{"action":"provision","args":{"unid":"01:1"}}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/pm820/do"
	parse_logger "${INVALID_UNID}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"provision","args":{"unid":"01:1"}}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/pm820/do"'")
	result_logs "modbus_provision_test" ${LOG_MODBUS_PROV}  ${start_time} "${pub}"
}

modbus_provision_test5()
{
	start_time=$(date | awk '{print $4}')  
	subscribe_sts_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"provision","args":{"unid":"01:1"}}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/pm820/do"
	parse_sts "${PROVISION_STATE}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"provision","args":{"unid":"01:1"}}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/pm820/do"'")
	result_logs "modbus_provision_test" ${LOG_MODBUS_PROV}  ${start_time} "${pub}"
}

modbus_provision_test6()
{
	start_time=$(date | awk '{print $4}')  
	subscribe_logger_event &  
	pids+=($!)
	mosquitto_pub -m '{"action":"provision","args":{"unid":"01:3"}}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/pm820/do"
	parse_logger "${SLAVE_ALREADY_PROV}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"provision","args":{"unid":"01:3"}}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/pm820/do"'")
	result_logs "modbus_provision_test" ${LOG_MODBUS_PROV}  ${start_time} "${pub}"
}

modbus_provision_test7()
{
	start_time=$(date | awk '{print $4}')  
	subscribe_logger_event &  
	pids+=($!)
	mosquitto_pub -m '{"action":"provision"}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/pm820/do"
	parse_logger
	result "logger"
	pub=("mosquitto_pub -m '{"action":"provision"}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/pm820/do"'")
	result_logs "modbus_provision_test" ${LOG_MODBUS_PROV}  ${start_time} "${pub}"
}

modbus_provision_test8()
{
	start_time=$(date | awk '{print $4}')  
	subscribe_logger_event &  
	pids+=($!)
	mosquitto_pub -m '{"action":"provision","args":{"unid":"17"}}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/pm820/do"
	parse_logger "${DEV_NOT_FOUND}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"provision","args":{"unid":"17"}}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/pm820/do"'")
	result_logs "modbus_provision_test" ${LOG_MODBUS_PROV}  ${start_time} "${pub}"
}

setup_time

modbus_provision_test1
modbus_provision_test2
modbus_provision_test3
modbus_provision_test4
modbus_provision_test5
modbus_provision_test6
modbus_provision_test7
modbus_provision_test8

kill_process

