#!/bin/bash

source env_var.sh
source ${IOX_PATH}"/common.sh"
source ${IOX_PATH}"/iox.config"
source ${IOX_PATH}"/errors.sh"

LOG_EVENT_LOGGER=${IOX_PATH}"/modbus/logger"
LOG_STS=${IOX_PATH}"/modbus/sts"
LOG_MODBUS_WINK=${IOX_PATH}"/modbus/modbus_wink_log"

modbus_wink_test1()
{
	start_time=$(date | awk '{print $4}')
	subscribe_logger_event & 
	pids+=($!)
	mosquitto_pub -m '{"action":"wink"}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/pm820/do"
	parse_logger "${WINK_NOT_FOUND}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"wink"}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/pm820/do"'")
	result_logs "modbus_wink_test" ${LOG_MODBUS_WINK}  ${start_time} "${pub}"
}

modbus_wink_test1

kill_process

