#!/bin/bash

source env_var.sh
source ${IOX_PATH}"/common.sh"
source ${IOX_PATH}"/iox.config"
source ${IOX_PATH}"/errors.sh"

LOG_EVENT_LOGGER=${IOX_PATH}"/modbus/logger"
LOG_STS=${IOX_PATH}"/modbus/sts"
LOG_MODBUS_TEST=${IOX_PATH}"/modbus/modbus_test_log"

mod_pm820_dev="pm820 : device not found"
mod_unprov_state="unprovisioned"
mod_prov_state="provisioned"

subscribe_sts_event()
{
	 mosquitto_sub -t "glp/0/${SID}/fb/dev/iox/pm820/sts" > ${STS_PATH} 
}

modbus_test_test1()
{
	start_time=$(date | awk '{print $4}') 
	subscribe_logger_event & 
	pids+=($!)
	mosquitto_pub -m '{"action":"test"}' -t "glp/0/${SID}/rq/dev/iox/pm820/do"
	parse_logger "${mod_pm820_dev}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"test"}' -t '"glp/0/${SID}/rq/dev/iox/pm820/do"'")
	result_logs "modbus_test_test" ${LOG_MODBUS_TEST}  ${start_time} "${pub}"
}

modbus_test_test2()
{
	start_time=$(date | awk '{print $4}') 
	subscribe_sts_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"test"}' -t "glp/0/${SID}/rq/dev/iox/pm820/do"
	parse_sts "${mod_unprov_state}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"test"}' -t '"glp/0/${SID}/rq/dev/iox/pm820/do"'")
	result_logs "modbus_test_test" ${LOG_MODBUS_TEST}  ${start_time} "${pub}"
}

modbus_test_test3()
{
	start_time=$(date | awk '{print $4}') 
	subscribe_sts_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"test"}' -t "glp/0/${SID}/rq/dev/iox/pm820/do"
	parse_sts "${mod_prov_state}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"test"}' -t '"glp/0/${SID}/rq/dev/iox/pm820/do"'")
	result_logs "modbus_test_test" ${LOG_MODBUS_TEST}  ${start_time} "${pub}"
}

modbus_test_test4()
{
	start_time=$(date | awk '{print $4}') 
	subscribe_sts_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"test"}' -t "glp/0/${SID}/rq/dev/iox/pm820/do"
	parse_sts "${mod_prov_state}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"test"}' -t '"glp/0/${SID}/rq/dev/iox/pm820/do"'")
	result_logs "modbus_test_test" ${LOG_MODBUS_TEST}  ${start_time} "${pub}"
}

modbus_test_test5()
{
	start_time=$(date | awk '{print $4}') 
	subscribe_sts_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"test"}' -t "glp/0/${SID}/rq/dev/iox/pm820/do"
	parse_sts "${mod_unprov_state}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"test"}' -t '"glp/0/${SID}/rq/dev/iox/pm820/do"'")
	result_logs "modbus_test_test" ${LOG_MODBUS_TEST}  ${start_time} "${pub}"
}

modbus_test_test6()
{
	start_time=$(date | awk '{print $4}') 
	subscribe_logger_event & 
	pids+=($!)
	mosquitto_pub -m '{"action":"test"}' -t "glp/0/${SID}/rq/dev/iox/pm820/do"
	parse_logger "${mod_pm820_dev}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"test"}' -t '"glp/0/${SID}/rq/dev/iox/pm820/do"'")
	result_logs "modbus_test_test" ${LOG_MODBUS_TEST}  ${start_time} "${pub}"
}

modbus_test_test1
modbus_test_test2
modbus_test_test3
modbus_test_test4
modbus_test_test5
modbus_test_test6

kill_process

