#!/bin/bash

source env_var.sh
source ${IOX_PATH}"/common.sh"
source ${IOX_PATH}"/iox.config"
source ${IOX_PATH}"/errors.sh"

LOG_EVENT_LOGGER=${IOX_PATH}"/modbus/logger"
LOG_STS=${IOX_PATH}"/modbus/sts"
LOG_MODBUS_DEPROV=${IOX_PATH}"/modbus/modbus_deprov_log"

subscribe_sts_event()
{
	 mosquitto_sub -t "glp/0/${SID}/fb/dev/${MODBUS_PROTOCOL}/pm820/sts" > ${STS_PATH} 
}

modbus_deprovision_test1()
{
	start_time=$(date | awk '{print $4}') 
	subscribe_logger_event & 
	pids+=($!)
	mosquitto_pub -m '{"action":"deprovision"}' -t "glp/0/${SID}/rq/dev/${MODBUS_PROTOCOL}/pm820/do"
	parse_logger "${DEV_NOT_FOUND}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"deprovision"}' -t '"glp/0/${SID}/rq/dev/${MODBUS_PROTOCOL}/pm820/do"'")
	result_logs "modbus_deprovision_test" ${LOG_MODBUS_DEPROV}  ${start_time} "${pub}"
}

modbus_deprovision_test2()
{
	start_time=$(date | awk '{print $4}') 
	subscribe_logger_event & 
	pids+=($!)
	mosquitto_pub -m '{"action":"deprovision"}' -t  "glp/0/${SID}/rq/dev/${MODBUS_PROTOCOL}/pm820/do" 
	parse_logger "${DEPROV_UNSUCCESSFUL}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"deprovision"}' -t  '"glp/0/${SID}/rq/dev/${MODBUS_PROTOCOL}/pm820/do"'")
	result_logs "modbus_deprovision_test" ${LOG_MODBUS_DEPROV}  ${start_time} "${pub}"
}

modbus_deprovision_test3()
{
	start_time=$(date | awk '{print $4}') 
	subscribe_sts_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"deprovision"}' -t "glp/0/${SID}/rq/dev/${MODBUS_PROTOCOL}/pm820/do"
	parse_sts "${UNPROVISION_STATE}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"deprovision"}' -t '"glp/0/${SID}/rq/dev/${MODBUS_PROTOCOL}/pm820/do"'")
	result_logs "modbus_deprovision_test" ${LOG_MODBUS_DEPROV}  ${start_time} "${pub}"
}


modbus_deprovision_test4()
{
	start_time=$(date | awk '{print $4}') 
	subscribe_logger_event & 
	pids+=($!)
	mosquitto_pub -m '{"action":"deprovision"}' -t "glp/0/${SID}/rq/dev/${MODBUS_PROTOCOL}/pm820/do"
	parse_logger "${DEPROV_UNSUCCESSFUL}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"deprovision"}' -t '"glp/0/${SID}/rq/dev/${MODBUS_PROTOCOL}/pm820/do"'")
	result_logs "modbus_deprovision_test" ${LOG_MODBUS_DEPROV}  ${start_time} "${pub}"
}

modbus_deprovision_test5()
{
	start_time=$(date | awk '{print $4}') 
	subscribe_logger_event & 
	pids+=($!)
	mosquitto_pub -m '{"action":"deprovision"}' -t "glp/0/${SID}/rq/dev/${MODBUS_PROTOCOL}/pm820/do"
	parse_logger "${DEV_NOT_FOUND}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"deprovision"}' -t '"glp/0/${SID}/rq/dev/${MODBUS_PROTOCOL}/pm820/do"'")
	result_logs "modbus_deprovision_test" ${LOG_MODBUS_DEPROV}  ${start_time} "${pub}"
}

setup_time

modbus_deprovision_test1
modbus_deprovision_test2
modbus_deprovision_test3
modbus_deprovision_test4
modbus_deprovision_test5

kill_process

