#!/bin/bash

modbus_dynamic_configure_test1()
{
	mosquitto_pub -m '{"baudrate":{"value":12345}}' -t "glp/0/17q2d9v/rq/dev/iox/sys/if/modbus/0"
}

modbus_dynamic_configure_test2()
{
	mosquitto_pub -m '{"baudrate":{"value":19200},"stopbits":{"value":12345}}' -t "glp/0/17q2d9v/rq/dev/iox/sys/if/modbus/0"
}

modbus_dynamic_configure_test3()
{
	mosquitto_pub -m '{"baudrate":{"value":19200},"stopbits":{"value":2},"parity":{"value":1234}}' -t "glp/0/17q2d9v/rq/dev/iox/sys/if/modbus/0"
}

modbus_dynamic_configure_test4()
{
	mosquitto_pub -m '{"baudrate":{"value":19200}}' -t "glp/0/17q2d9v/rq/dev/iox/sys/if/modbus/0"
}

modbus_dynamic_configure_test5()
{
	mosquitto_pub -m '{"baudrate":{"value":19200},"stopbits":{"value":2},"parity":{"value":0}}' -t "glp/0/17q2d9v/rq/dev/iox/sys/if/modbus/0"
	mosquitto_pub -m '{"action":"reset"}' -t "glp/0/17q2d9v/rq/dev/iox/sys/do"
}

modbus_dynamic_configure_test6()
{
	mosquitto_pub -m '{"baudrate":{"value":9600}}' -t "glp/0/17q2d9v/rq/dev/iox/sys/if/modbus/0"
	mosquitto_pub -m '{"action":"reset"}' -t "glp/0/17q2d9v/rq/dev/iox/sys/do"
}

modbus_dynamic_configure_test7()
{
	mosquitto_pub -m '1' -t "glp/0/17q2d9v/rq/dev/iox/sys/if/modbus/0/stopbits/value"
	mosquitto_pub -m '{"action":"reset"}' -t "glp/0/17q2d9v/rq/dev/iox/sys/do"
}

modbus_dynamic_configure_test8()
{
	mosquitto_pub -m '{"baudrate":{"value":115200},"stopbits":{"value":1},"parity":{"value":2}}' -t "glp/0/17q2d9v/rq/dev/iox/sys/if/modbus/0"
	mosquitto_pub -m '{"action":"reset"}' -t "glp/0/17q2d9v/rq/dev/iox/sys/do"
}
	
modbus_dynamic_configure_test1
modbus_dynamic_configure_test2
modbus_dynamic_configure_test3
modbus_dynamic_configure_test4
modbus_dynamic_configure_test5
modbus_dynamic_configure_test6
modbus_dynamic_configure_test7
modbus_dynamic_configure_test8



