#!/bin/bash

LOGGER_PATH="/home/unmesh/iox_test/modbus/logger"

kill_process()
{
	pkill mosquitto_sub 
	if [[ $? -eq 1 ]];
	then
		echo "failed to kill mosquitto_sub process"
	fi
}

parse_logger()
{
	sleep 5
	if [[ -s ${LOGGER_PATH} ]];
	then 
		out=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${LOGGER_PATH})
		out_time=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | awk '{print $2}')
		if [[ ${last_out_time} == ${out_time} ]];
		then
			echo "NO NEW MESSAGE FROM LOGGER"
		else
			parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
			if [[ ${parse} == ${1} ]];
			then
				LOGGER_RESULT="PASS"
			else
				LOGGER_RESULT="FAIL"
			fi
			last_out_time=${out_time}
		fi
	fi
	rm ${LOGGER_PATH}
}

subscribe_logger_event()
{
    mosquitto_sub -t "glp/0/./=logger/event" > ${LOGGER_PATH}
}

modbus_deep_test1()
{
	subscribe_logger_event &
	mosquitto_pub -m '{"Voltage_A-B":{"monitor":{"rate":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/dummy/if/block/7"
	parse_logger
}

modbus_deep_test2()
{
	subscribe_logger_event &
	mosquitto_pub -m '{"dummy":{"monitor":{"rate":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/dummy/if/block/1"
	parse_logger
}
	
modbus_deep_test3()
{
	subscribe_logger_event &
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/if/block/1" &
	mosquitto_pub -m '{"Voltage_A-B":{"monitor":{"rate":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/if/block/1"
	parse_logger
}

modbus_deep_test4()
{
	subscribe_logger_event &
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/if/block/1" &
	mosquitto_pub -m '{"monitor":{"rate":20}}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/if/block/1/Voltage_A-B"
	parse_logger
}

modbus_deep_test5()
{
	subscribe_logger_event &
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/if/block/1" &
	mosquitto_pub -m '{"rate":30}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/if/block/1/Voltage_A-B/monitor" 
	parse_logger
}

modbus_deep_test6()
{
	subscribe_logger_event &
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/if/block/1" &
	mosquitto_pub -m '40' -t "glp/0/17q2d9v/rq/dev/iox/pm820/if/block/1/Voltage_A-B/monitor/rate"
	parse_logger
}

modbus_deep_test1
modbus_deep_test2
modbus_deep_test3
modbus_deep_test4
modbus_deep_test5
modbus_deep_test6

kill_process

