#!/bin/bash

source env_var.sh
source ${IOX_PATH}"/common.sh"
source ${IOX_PATH}"/iox.config"
source ${IOX_PATH}"/errors.sh"

LOG_EVENT_LOGGER=${IOX_PATH}"/modbus/logger"
LOG_STS=${IOX_PATH}"/modbus/sts"
LOG_MODBUS_MSG=${IOX_PATH}"/modbus/modbus_msg_log"

modbus_message_test1()
{
	start_time=$(date | awk '{print $4}')
	subscribe_logger_event & 
	pids+=($!)
	mosquitto_pub -m '{"action":"message"}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
	parse_logger
	result "logger"
	pub=("mosquitto_pub -m '{"action":"message"}' -t '"glp/0/17q2d9v/rq/dev/iox/pm820/do"'")
	result_logs "modbus_message_test" ${LOG_MODBUS_MSG}  ${start_time} "${pub}"
}


modbus_message_test1

kill_process

