#!/bin/bash

source env_var.sh
source ${IOX_PATH}"/common.sh"
source ${IOX_PATH}"/iox.config"
source ${IOX_PATH}"/errors.sh"

LOG_EVENT_LOGGER=${IOX_PATH}"/modbus/logger"
LOG_STS=${IOX_PATH}"/modbus/sts"
LOG_MODBUS_DEL=${IOX_PATH}"/modbus/modbus_del_log"

mod_pm820_dev="pm820 : device not found"
mod_del_unsuccess="delete : action unsuccessful"
mod_del_state="deleted"

subscribe_sts_event()
{
	 mosquitto_sub -t "glp/0/${SID}/fb/dev/${IOX_PROTOCOL}/pm820/sts" > ${STS_PATH} 
}

modbus_delete_test1()
{
	start_time=$(date | awk '{print $4}') 
	subscribe_logger_event & 
	pids+=($!)
	mosquitto_pub -m '{"action":"delete"}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/pm820/do"
	parse_logger "${mod_pm820_dev}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"delete"}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/pm820/do"'")
	result_logs "modbus_delete_test" ${LOG_MODBUS_DEL}  ${start_time} "${pub}"
}

modbus_delete_test2()
{
	start_time=$(date | awk '{print $4}') 
	subscribe_sts_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"delete"}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/pm820/do"
	parse_sts "${mod_del_state}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"delete"}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/pm820/do"'")
	result_logs "modbus_delete_test" ${LOG_MODBUS_DEL}  ${start_time} "${pub}"
}

modbus_delete_test3()
{
	start_time=$(date | awk '{print $4}') 
	subscribe_logger_event & 
	pids+=($!)
	mosquitto_pub -m '{"action":"delete"}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/pm820/do"
	parse_logger "${mod_del_unsuccess}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"delete"}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/pm820/do"'")
	result_logs "modbus_delete_test" ${LOG_MODBUS_DEL}  ${start_time} "${pub}"
}


modbus_delete_test4()
{
	start_time=$(date | awk '{print $4}') 
	subscribe_sts_event &
	pids+=($!)
	mosquitto_pub -m '{"action":"delete"}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/pm820/do"
	parse_sts "${mod_del_state}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"delete"}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/pm820/do"'")
	result_logs "modbus_delete_test" ${LOG_MODBUS_DEL}  ${start_time} "${pub}"
}

modbus_delete_test5()
{
	start_time=$(date | awk '{print $4}') 
	subscribe_logger_event & 
	pids+=($!)
	mosquitto_pub -m '{"action":"delete"}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/pm820/do"
	parse_logger "${mod_pm820_dev}"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"delete"}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/pm820/do"'")
	result_logs "modbus_delete_test" ${LOG_MODBUS_DEL}  ${start_time} "${pub}"
}

setup_time

modbus_delete_test1
modbus_delete_test2
modbus_delete_test3
modbus_delete_test4
modbus_delete_test5

kill_process

