#!/bin/bash

LOGGER_PATH="/home/unmesh/iox_test/modbus/logger"
STS_PATH="/home/unmesh/iox_test/modbus/sts"

kill_process()
{
	pkill mosquitto_sub 
	if [[ $? -eq 1 ]];
	then
		echo "failed to kill mosquitto_sub process"
	fi
}

parse_logger()
{
	sleep 5
	if [[ -s ${LOGGER_PATH} ]];
	then 
		out=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${LOGGER_PATH})
		out_time=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | awk '{print $2}')
		if [[ ${last_out_time} == ${out_time} ]];
		then
			echo "NO NEW MESSAGE FROM LOGGER"
		else
			parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
			if [[ ${parse} == ${1} ]];
			then
				LOGGER_RESULT="PASS"
			else
				LOGGER_RESULT="FAIL"
			fi
			last_out_time=${out_time}
		fi
	fi
	rm ${LOGGER_PATH}
}

parse_sts()
{
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/sts" > ${STS_PATH} &
	sleep 5
	if [[ -s ${STS_PATH} ]];
	then 
		out=$(awk -F "," '/mru/{print $NF}' ${STS_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${STS_PATH})
		sleep 2
		state=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["state"]')
		if [[ ${state} == "unprovisioned" ]];
		then
			STS_RESULT="PASS"
		else
			STS_RESULT="FAIL"
		fi
	fi
	rm ${STS_PATH}
}

subscribe_logger_event()
{
    mosquitto_sub -t "glp/0/./=logger/event" > ${LOGGER_PATH}
}

subscribe_sts_event()
{
	 mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/sts" > ${STS_PATH} 
}

modbus_provision_test1()
{
	subscribe_logger_event &
	mosquitto_pub -m '{"action":"provision","args":{"unid":"01:1"}}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
	parse_logger
}

modbus_provision_test2()
{
	subscribe_logger_event &
	mosquitto_pub -m '{"action":"provision","args":{}}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
	parse_logger
}

modbus_provision_test3()
{
	subscribe_logger_event &
	mosquitto_pub -m '{"action":"provision","args":{"unid":"3000"}}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
	parse_logger
}

modbus_provision_test4()
{
	subscribe_logger_event &
	mosquitto_pub -m '{"action":"provision","args":{"unid":"01:1"}}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
	parse_logger
}

modbus_provision_test5()
{
	subscribe_sts_event &
	mosquitto_pub -m '{"action":"provision","args":{"unid":"01:1"}}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
	parse_sts
}

modbus_provision_test6()
{
	subscribe_logger_event &
	mosquitto_pub -m '{"action":"provision","args":{"unid":"01:3"}}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
	parse_logger
}

modbus_provision_test7()
{
	subscribe_logger_event &
	mosquitto_pub -m '{"action":"provision"}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
	parse_logger
}

modbus_provision_test8()
{
	subscribe_logger_event &
	mosquitto_pub -m '{"action":"provision","args":{"unid":"17"}}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
	parse_logger
}

modbus_provision_test1
modbus_provision_test2
modbus_provision_test3
modbus_provision_test4
modbus_provision_test5
modbus_provision_test6
modbus_provision_test7
modbus_provision_test8

kill_process

