#!/bin/bash

LOGGER_PATH="/home/unmesh/iox_test/modbus/logger"

kill_process()
{
	pkill mosquitto_sub
	if [[ $? -eq 0 ]];
	then
		echo "mosquitto_sub process killed"
	else
		echo "failed to kill mosquitto_sub process"
	fi
	rm ${LOGGER_PATH}
}

parse_logger()
{
	sleep 5
	if [[ -s ${LOGGER_PATH} ]];
	then 
		out=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${LOGGER_PATH})
		parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
		echo "parse : "${parse}
	fi
}

parse_sts()
{
	sleep 5
	if [[ -s ${STS_PATH} ]];
	then 
		out=$(awk -F "," '/mru/{print $NF}' ${STS_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${STS_PATH})
		sleep 2
		state=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["state"]')
		echo "state : "${state}
	fi
}


modbus_deep_test1()
{
	echo "test1 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"Voltage_A-B":{"monitor":{"rate":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/dummy/if/block/7"
	parse_logger
}

modbus_deep_test2()
{
	echo "test2 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"dummy":{"monitor":{"rate":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/dummy/if/block/1"
	parse_logger
}
	
modbus_deep_test3()
{
	echo "test3 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/if/block/1" &
	mosquitto_pub -m '{"Voltage_A-B":{"monitor":{"rate":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/if/block/1"
	parse_logger
}

modbus_deep_test4()
{
	echo "test4 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/if/block/1" &
	mosquitto_pub -m '{"monitor":{"rate":20}}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/if/block/1/Voltage_A-B"
	parse_logger
}

modbus_deep_test5()
{
	echo "test5 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/if/block/1" &
	mosquitto_pub -m '{"rate":30}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/if/block/1/Voltage_A-B/monitor" 
	parse_logger
}

modbus_deep_test6()
{
	echo "test6 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/pm820/if/block/1" &
	mosquitto_pub -m '40' -t "glp/0/17q2d9v/rq/dev/iox/pm820/if/block/1/Voltage_A-B/monitor/rate"
	parse_logger
}

modbus_deep_test1
modbus_deep_test2
modbus_deep_test3
modbus_deep_test4
modbus_deep_test5
modbus_deep_test6

kill_process
