#!/bin/bash

source env_var.sh
source ${IOX_PATH}"/common.sh"
source ${IOX_PATH}"/iox.config"
source ${IOX_PATH}"/errors.sh"

LOG_EVENT_LOGGER=${IOX_PATH}"/modbus/logger"
LOG_STS=${IOX_PATH}"/modbus/sts"
LOG_MODBUS_RESET=${IOX_PATH}"/modbus/modbus_reset_log"

modbus_reset_test1()
{
	start_time=$(date | awk '{print $4}')
	subscribe_logger_event & 
	pids+=($!)
	mosquitto_pub -m '{"action":"reset"}' -t "glp/0/17q2d9v/rq/dev/iox/pm820/do"
	parse_logger "reset : action not found"
	result "logger"
	pub=("mosquitto_pub -m '{"action":"reset"}' -t '"glp/0/17q2d9v/rq/dev/iox/pm820/do"'")
	result_logs "modbus_reset_test" ${LOG_MODBUS_RESET}  ${start_time} "${pub}"
}

modbus_reset_test1

kill_process

