#!/bin/bash

LOGGER_PATH="/home/unmesh/iox_test/dio/do/logger"

kill_process()
{
    pkill mosquitto_sub
    if [[ $? -eq 0 ]];
    then
        echo "mosquitto_sub process killed"
    else
        echo "failed to kill mosquitto_sub process"
    fi
	rm ${LOGGER_PATH}
}

parse_logger()
{
	sleep 5
	if [[ -s ${LOGGER_PATH} ]];
	then 
		out=$(grep 'utc' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 -B4 -A1 "regex" ${LOGGER_PATH})
		parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
		echo "parse : "${parse}
	fi
}

do_device_test1()
{

	echo "test1 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"do-val":{"value":{"type":"level","level":true,"frequency":10,"pulse":300,"pwm":{"frequency":20000,"duty-cycle":90}}}}' -t "glp/0/17q2d9v/rq/dev/iox/meter/if/do/1"

	parse_logger
}

do_device_test2()
{

	echo "test2 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/do/1" >> ${LOGGER_PATH}  &
	mosquitto_pub -m '{"do-val":{"value":{"type":"level","level":true,"frequency":10,"pulse":300,"pwm":{"frequency":20000,"duty-cycle":90}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/1"
	
	parse_logger

}

do_device_test1
do_device_test2

kill_process
