#!/bin/bash

source env_var.sh
source ${IOX_PATH}"/common.sh"
source ${IOX_PATH}"/iox.config"
source ${IOX_PATH}"/errors.sh"

LOG_EVENT_LOGGER=${IOX_PATH}"/dio/do/logger"
LOG_STS=${IOX_PATH}"/dio/do/sts"
LOG_DO_DEVICE=${IOX_PATH}"/dio/do/do_device_log"



do_device_test1()
{
	start_time=$(date | awk '{print $4}')
  	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"do-val":{"value":{"type":"level","level":true,"frequency":10,"pulse":300,"pwm":{"frequency":20000,"duty-cycle":90}}}}' -t "glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/if/do/1"
	parse_logger
	result "logger"
	pub=("mosquitto_pub -m '{"do-val":{"value":{"type":"level","level":true,"frequency":10,"pulse":300,"pwm":{"frequency":20000,"duty-cycle":90}}}}' -t '"glp/0/${SID}/rq/dev/iox/${METER_DEV_NAME}/if/do/1"'")
	result_logs "do_device_test" ${LOG_DO_DEVICE}  ${start_time} "${pub}"
}

do_device_test2()
{
	subscribe_logger_event &
#	mosquitto_sub -t "glp/0/${SID}/fb/dev/iox/${DIO_DEV_NAME}/if/do/1" > ${LOGGER_PATH}  &
	mosquitto_pub -m '{"do-val":{"value":{"type":"level","level":true,"frequency":10,"pulse":300,"pwm":{"frequency":20000,"duty-cycle":90}}}}' -t "glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/if/do/1"
	parse_logger
	result "logger"
	pub=("mosquitto_pub -m '{"do-val":{"value":{"type":"level","level":true,"frequency":10,"pulse":300,"pwm":{"frequency":20000,"duty-cycle":90}}}}' -t '"glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/if/do/1"'")
	result_logs "do_device_test" ${LOG_DO_DEVICE}  ${start_time} "${pub}"
}

setup_time

do_device_test1
do_device_test2

kill_process

