#!/bin/bash

source env_var.sh
source ${IOX_PATH}"/common.sh"
source ${IOX_PATH}"/iox.config"
source ${IOX_PATH}"/errors.sh"

LOG_EVENT_LOGGER=${IOX_PATH}"/dio/do/logger"
LOG_STS=${IOX_PATH}"/dio/do/sts"
LOG_DO_DEEP=${IOX_PATH}"/dio/do/do_deep_log"

do_deep_test1()
{
	start_time=$(date | awk '{print $4}')
  	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"frequency":10}' -t "glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/if/dqo/1/do-val/value"
	parse_logger
	result "logger"
	pub=("mosquitto_pub -m '{"frequency":10}' -t '"glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/if/dqo/1/do-val/value"'")
	result_logs "do_deep_test" ${test_num} ${LOG_DO_DEEP}  ${start_time} "${pub}"

}

do_deep_test2()
{
	start_time=$(date | awk '{print $4}')
  	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"frequency":10}' -t "glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/if/do/1/do-val123/value"
	parse_logger
	result "logger"
	pub=("mosquitto_pub -m '{"frequency":10}' -t '"glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/if/do/1/do-val123/value"'")
	result_logs "do_deep_test" ${test_num} ${LOG_DO_DEEP}  ${start_time} "${pub}"

}


do_deep_test3()
{
	start_time=$(date | awk '{print $4}')
  	subscribe_logger_event &
	pids+=($!)
#	mosquitto_sub -t "glp/0/${SID}/fb/dev/iox/${DIO_DEV_NAME}/if/do/1" &
	mosquitto_pub -m '{"do-val":{"value":{"type":"frequency","level":false,"frequency":10,"pulse":300,"pwm":{"frequency":20000,"duty-cycle":90}}}}' -t "glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/if/do/1"
	parse_logger
	result "logger"
	pub=("mosquitto_pub -m '{"do-val":{"value":{"type":"frequency","level":false,"frequency":10,"pulse":300,"pwm":{"frequency":20000,"duty-cycle":90}}}}' -t '"glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/if/do/1"'")
	result_logs "do_deep_test" ${test_num} ${LOG_DO_DEEP}  ${start_time} "${pub}"
}

do_deep_test4()
{
	start_time=$(date | awk '{print $4}')
  	subscribe_logger_event &
	pids+=($!)
#	mosquitto_sub -t "glp/0/${SID}/fb/dev/iox/${DIO_DEV_NAME}/if/do/1" &
	mosquitto_pub -m '{"value":{"type":"frequency","level":false,"frequency":1,"pulse":300,"pwm":{"frequency":20000,"duty-cycle":90}}}' -t "glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/if/do/1/do-val"
	parse_logger
	result "logger"
	pub=("mosquitto_pub -m '{"value":{"type":"frequency","level":false,"frequency":1,"pulse":300,"pwm":{"frequency":20000,"duty-cycle":90}}}' -t '"glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/if/do/1/do-val"'")
	result_logs "do_deep_test" ${test_num} ${LOG_DO_DEEP}  ${start_time} "${pub}"

}

do_deep_test5()
{	
	start_time=$(date | awk '{print $4}')
  	subscribe_logger_event &
	pids+=($!)
#	mosquitto_sub -t "glp/0/${SID}/fb/dev/iox/${DIO_DEV_NAME}/if/do/1" &
	mosquitto_pub -m '{"frequency":10}' -t "glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/if/do/1/do-val/value"
	parse_logger
	result "logger"
	pub=("mosquitto_pub -m '{"frequency":10}' -t '"glp/0/${SID}/rq/dev/iox/${DIO_DEV_NAME}/if/do/1/do-val/value"'")
	result_logs "do_deep_test" ${test_num} ${LOG_DO_DEEP}  ${start_time} "${pub}"
}


setup_time

do_deep_test1
do_deep_test2
do_deep_test3
do_deep_test4
do_deep_test5

kill_process

