#!/bin/bash

kill_process()
{
    pkill mosquitto_sub
    if [[ $? -eq 0 ]];
    then
        echo "mosquitto_sub process killed"
    else
        echo "failed to kill mosquitto_sub process"
    fi
}

do_get_test1()
{	

	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox/dio/if/do/1/do-val"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"

}

do_get_test2()
{

	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox12/dio/if/do/1/do-val"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"

}

do_get_test3()
{

	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox/dio12/if/do/1/do-val"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"

}

do_get_test4()
{

	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox/dio/if/do/8/do-val"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"

}

do_get_test5()
{
	
	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox/dio/if/do/8/do-val"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"

}

do_get_test6()
{

	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox/dio/if/do/1/do-val","dev/iox/dio/if/do/2/do-val"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"

}

do_get_test1
do_get_test2
do_get_test3
do_get_test4
do_get_test5
do_get_test6

sleep 10
kill_process
