#!/bin/bash

LOGGER_PATH="/home/unmesh/iox_test/dio/do/logger"

kill_process()
{
	pkill mosquitto_sub 
	if [[ $? -eq 1 ]];
	then
		echo "failed to kill mosquitto_sub process"
	fi
}

parse_logger()
{
	sleep 5
	if [[ -s ${LOGGER_PATH} ]];
	then 
		out=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${LOGGER_PATH})
		out_time=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | awk '{print $2}')
		if [[ ${last_out_time} == ${out_time} ]];
		then
			echo "NO NEW MESSAGE FROM LOGGER"
		else
			parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
			if [[ ${parse} == ${1} ]];
			then
				LOGGER_RESULT="PASS"
			else
				LOGGER_RESULT="FAIL"
			fi
			last_out_time=${out_time}
		fi
	fi
	rm ${LOGGER_PATH}
}

subscribe_logger_event()
{
    mosquitto_sub -t "glp/0/./=logger/event" > ${LOGGER_PATH}
}


do_port_test1()
{
	subscribe_logger_event &
#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/do/1" &
	mosquitto_pub -m '{"do-val":{"value":{"type":"level","level":true,"frequency":0,"pulse":0,"pwm":{"frequency":0,"duty-cycle":0}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/1"
	parse_logger
}

do_port_test2()
{
	subscribe_logger_event &
#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/do/2" &
	mosquitto_pub -m '{"do-val":{"value":{"type":"level","level":true,"frequency":0,"pulse":0,"pwm":{"frequency":0,"duty-cycle":0}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/2"
	parse_logger
}

do_port_test3()
{
	subscribe_logger_event &
#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/do/3" &
	mosquitto_pub -m '{"do-val":{"value":{"type":"level","level":true,"frequency":0,"pulse":0,"pwm":{"frequency":0,"duty-cycle":0}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/3"
	parse_logger
}

do_port_test4()
{
	subscribe_logger_event &
#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/do/4" &
	mosquitto_pub -m '{"do-val":{"value":{"type":"level","level":true,"frequency":0,"pulse":0,"pwm":{"frequency":0,"duty-cycle":0}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/4"
	parse_logger
}

do_port_test5()
{
	subscribe_logger_event &
#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/do/5" &
	mosquitto_pub -m '{"do-val":{"value":{"type":"level","level":true,"frequency":0,"pulse":0,"pwm":{"frequency":0,"duty-cycle":0}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/5"
	parse_logger
}

do_port_test6()
{
	subscribe_logger_event &
#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/do/6" &
	mosquitto_pub -m '{"do-val":{"value":{"type":"level","level":true,"frequency":0,"pulse":0,"pwm":{"frequency":0,"duty-cycle":0}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/6"
	parse_logger
}

do_port_test7()
{
	subscribe_logger_event &
#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/do/8" &
	mosquitto_pub -m '{"do-val":{"value":{"type":"level","level":true,"frequency":0,"pulse":0,"pwm":{"frequency":0,"duty-cycle":0}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/8"
	parse_logger
}

do_port_test1
do_port_test2
do_port_test3
do_port_test4
do_port_test5
do_port_test6
do_port_test7

kill_process

