#!/bin/bash

source env_var.sh
source ${IOX_PATH}"/common.sh"
source ${IOX_PATH}"/iox.config"
source ${IOX_PATH}"/errors.sh"

LOG_EVENT_LOGGER=${IOX_PATH}"/dcm/logger"
LOG_STS=${IOX_PATH}"/dcm/sts"
LOG_DCM_CREATE=${IOX_PATH}"/dcm/dcm_create_log"

dcm_fail_state="failed"
dcm_create_state="created"


dcm_create_test1()
{
	start_time=$(date | awk '{print $4}')
	mosquitto_sub -t "glp/0/${SID}/fb/con/test0/sts" > ${LOG_STS} &
	pids+=($!)
	mosquitto_sub -t "glp/0/${SID}/fb/con/test0/cfg" &
	pids+=($!)
	mosquitto_pub -m '{"action":"create","args":{"sources":["glp/0/${SID}/fb/dev/${IOX_PROTOCOL}/dio/if/di/1/di-val123/value"],"destinations":["glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/dio/if/relay/1/relay-val/value"],"policy":"smart","map":{"level":"$.di-level.level"}}}' -t "glp/0/${SID}/rq/con/test0/do"
	parse_sts "${dcm_fail_state}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"create","args":{"sources":["glp/0/${SID}/fb/dev/${IOX_PROTOCOL}/dio/if/di/1/di-val123/value"],"destinations":["glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/dio/if/relay/1/relay-val/value"],"policy":"smart","map":{"level":"$.di-level.level"}}}' -t '"glp/0/${SID}/rq/con/test0/do"'")
	result_logs "dcm_create_test" ${LOG_DCM_CREATE}  ${start_time} "${pub}"
}

dcm_create_test2()
{
	start_time=$(date | awk '{print $4}')
	mosquitto_pub -m '{"action":"create","args":{"sources":[],"destinations":["glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/dio/if/relay/0/relay-val/value"],"policy":"smart","map":{"level":"$.di-level.level"}}}' -t "glp/0/${SID}/rq/con/test0/do"

}

dcm_create_test3()
{
	start_time=$(date | awk '{print $4}')
	mosquitto_pub -m '{"action":"create","args":{"sources":["glp/0/${SID}/fb/dev/${IOX_PROTOCOL}/dio/if/di/0/di-val/value"],"destinations":[],"policy":"smart","map":{"level":"$.di-level.level"}}}' -t "glp/0/${SID}/rq/con/test0/do"

}

dcm_create_test4()
{
	start_time=$(date | awk '{print $4}')
	mosquitto_sub -t "glp/0/${SID}/fb/con/test2/sts" > ${LOG_STS} & 
	pids+=($!)
	mosquitto_sub -t "glp/0/${SID}/fb/con/test2/cfg" &
	pids+=($!)
	mosquitto_pub -m '{"action":"create","args":{"sources":["glp/0/${SID}/fb/dev/${IOX_PROTOCOL}/dio/if/di/1/di-val/value"],"destinations":["glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/dio/if/relay/1/relay-val/value"],"policy":"smart","map":{"level":"$.di-level.level"}}}' -t "glp/0/${SID}/rq/con/test2/do"
	parse_sts "${dcm_create_state}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"create","args":{"sources":["glp/0/${SID}/fb/dev/${IOX_PROTOCOL}/dio/if/di/1/di-val/value"],"destinations":["glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/dio/if/relay/1/relay-val/value"],"policy":"smart","map":{"level":"$.di-level.level"}}}' -t '"glp/0/${SID}/rq/con/test2/do"'")
	result_logs "dcm_create_test" ${LOG_DCM_CREATE}  ${start_time} "${pub}"
}

dcm_create_test1
dcm_create_test2
dcm_create_test3
dcm_create_test4

kill_process

