#!/bin/bash

source env_var.sh
source ${IOX_PATH}"/common.sh"
source ${IOX_PATH}"/iox.config"
source ${IOX_PATH}"/errors.sh"

LOG_EVENT_LOGGER=${IOX_PATH}"/dcm/logger"
LOG_STS=${IOX_PATH}"/dcm/sts"
LOG_DCM_PROV=${IOX_PATH}"/dcm/dcm_prov_log"

dcm_prov_state="provisioning"

subscribe_sts_event()
{
	 mosquitto_sub -t "glp/0/${SID}/fb/con/test2/sts" > ${STS_PATH} 
}

dcm_provision_test1()
{
	start_time=$(date | awk '{print $4}')
	mosquitto_pub -m '{"action":"provision"}' -t "glp/0/${SID}/rq/con/test10/do"

}

dcm_provision_test2()
{
	start_time=$(date | awk '{print $4}')
	subscribe_sts_event &
	mosquitto_pub -m '' -t "glp/0/${SID}/rq/con/test2/do"
	parse_sts "${dcm_prov_state}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"prov"}' -t '"glp/0/${SID}/rq/con/test20/do"'")
	result_logs "dcm_prov_test" ${LOG_DCM_PROV}  ${start_time} "${pub}"
}

dcm_provision_test3()
{
	start_time=$(date | awk '{print $4}')
	subscribe_sts_event &
	mosquitto_sub -t "glp/0/${SID}/fb/con/test2/cfg" &
	mosquitto_pub -m '{"action":"provision"}' -t "glp/0/${SID}/rq/con/test2/do"
	parse_sts "${dcm_prov_state}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"prov"}' -t '"glp/0/${SID}/rq/con/test20/do"'")
	result_logs "dcm_prov_test" ${LOG_DCM_PROV}  ${start_time} "${pub}"
}

setup_time

dcm_provision_test1
dcm_provision_test2
dcm_provision_test3

kill_process

