#!/bin/bash

LOGGER_PATH="/home/unmesh/iox_test/dcm/logger"
STS_PATH="/home/unmesh/iox_test/dcm/sts"

kill_process()
{
	pkill mosquitto_sub
	if [[ $? -eq 0 ]];
	then
		echo "mosquitto_sub process killed"
	else
		echo "failed to kill mosquitto_sub process"
	fi
	rm ${STS_PATH}
}

parse_logger()
{
	sleep 5
	if [[ -s ${LOGGER_PATH} ]];
	then 
		out=$(grep 'utc' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 -B4 -A1 "regex" ${LOGGER_PATH})
		parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
		echo "parse : "${parse}
	fi
}

parse_sts()
{
	sleep 5
	if [[ -s ${STS_PATH} ]];
	then 
		out=$(grep 'mru' ${STS_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 -B11 -A1 "regex" ${STS_PATH})
		sleep 2
		state=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["state"]')
		echo "state : "${state}
	fi
}
dcm_create_test1()
{
	mosquitto_sub -t "glp/0/17q2d9v/fb/con/test0/sts" > ${STS_PATH} &
	msqouitto_sub -t "glp/0/17q2d9v/fb/con/test0/cfg" &
	mosquitto_pub -m '{"action":"create","args":{"sources":["glp/0/17q2d9v/fb/dev/iox.411b19/dio/if/di/1/di-val123/value"],"destinations":["glp/0/17q2d9v/rq/dev/iox.411b19/dio/if/relay/1/relay-val/value"],"policy":"smart","map":{"level":"$.di-level.level"}}}' -t "glp/0/17q2d9v/rq/con/test0/do"
	parse_sts
}

dcm_create_test2()
{
	mosquitto_sub -t "" &
	mosquitto_pub -m '{"action":"create","args":{"sources":[],"destinations":["glp/0/17q2d9v/rq/dev/iox.411b19/dio/if/relay/0/relay-val/value"],"policy":"smart","map":{"level":"$.di-level.level"}}}' -t "glp/0/17q2d9v/rq/con/test0/do"

}

dcm_create_test3()
{
	mosquitto_sub -t "" &
	mosquitto_pub -m '{"action":"create","args":{"sources":["glp/0/17q2d9v/fb/dev/iox.411b19/dio/if/di/0/di-val/value"],"destinations":[],"policy":"smart","map":{"level":"$.di-level.level"}}}' -t "glp/0/17q2d9v/rq/con/test0/do"

}

dcm_create_test4()
{
	mosquitto_sub -t "glp/0/17q2d9v/fb/con/test2/sts" > ${STS_PATH} & 
	mosquitto_sub -t "glp/0/17q2d9v/fb/con/test2/cfg" &
	mosquitto_pub -m '{"action":"create","args":{"sources":["glp/0/17q2d9v/fb/dev/iox.411b19/dio/if/di/1/di-val/value"],"destinations":["glp/0/17q2d9v/rq/dev/iox.411b19/dio/if/relay/1/relay-val/value"],"policy":"smart","map":{"level":"$.di-level.level"}}}' -t "glp/0/17q2d9v/rq/con/test2/do"
	parse_sts
}

dcm_create_test1
dcm_create_test2
dcm_create_test3
dcm_create_test4

kill_process
