#!/bin/bash

LOGGER_PATH="/home/unmesh/iox_test/dcm/logger"
STS_PATH="/home/unmesh/iox_test/dcm/sts"

kill_process()
{
	pkill mosquitto_sub 
	if [[ $? -eq 1 ]];
	then
		echo "failed to kill mosquitto_sub process"
	fi
}


parse_sts()
{
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/sts" > ${STS_PATH} &
	sleep 5
	if [[ -s ${STS_PATH} ]];
	then 
		out=$(awk -F "," '/mru/{print $NF}' ${STS_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${STS_PATH})
		sleep 2
		state=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["state"]')
		if [[ ${state} == "unprovisioned" ]];
		then
			STS_RESULT="PASS"
		else
			STS_RESULT="FAIL"
		fi
	fi
	rm ${STS_PATH}
}

subscribe_sts_event()
{
	 mosquitto_sub -t "glp/0/17q2d9v/fb/con/test1/sts" > ${STS_PATH} 
}

dcm_Provision_test1()
{
	mosquitto_pub -m '{"action":"provision"}' -t "glp/0/17q2d9v/rq/con/test3/do"
}

dcm_Provision_test2()
{	
	subscribe_sts_event &
	mosquitto_pub -m '{"action":"provision"}' -t "glp/0/17q2d9v/rq/con/test1/do"
	parse_sts
}

dcm_Provision_test3()
{
	subscribe_sts_event &
	mosquitto_sub -t "glp/0/17q2d9v/fb/con/test1/cfg" &
	mosquitto_pub -m '{"action":"provision"}' -t "glp/0/17q2d9v/rq/con/test1/do"
	parse_sts
}

dcm_Provision_test1
dcm_Provision_test2
dcm_Provision_test3

kill_process

