#!/bin/bash

source env_var.sh
source ${IOX_PATH}"/common.sh"
source ${IOX_PATH}"/iox.config"
source ${IOX_PATH}"/errors.sh"

LOG_EVENT_LOGGER=${IOX_PATH}"/dcm/logger"
LOG_STS=${IOX_PATH}"/dcm/sts"
LOG_DCM_DELETE=${IOX_PATH}"/dcm/dcm_delete_log"

dcm_del_state="deleted"

dcm_delete_test1()
{
	mosquitto_pub -m '{"action":"delete"}' -t "glp/0/17q2d9v/rq/con/test30/do"
}

dcm_delete_test2()
{
	start_time=$(date | awk '{print $4}')
	mosquitto_sub -t "glp/0/17q2d9v/fb/con/test20/sts" > ${STS_PATH} &
	pids+=($!)
	mosquitto_sub -t "glp/0/17q2d9v/fb/con/test20/cfg" &
	pids+=($!)
	mosquitto_pub -m '{"action":"delete"}' -t "glp/0/17q2d9v/rq/con/test20/do"
	parse_sts "${dcm_del_state}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"delete"}' -t '"glp/0/17q2d9v/rq/con/test20/do"'")
	result_logs "dcm_delete_test" ${LOG_DCM_DELETE}  ${start_time} "${pub}"
}

dcm_delete_test3()
{
	start_time=$(date | awk '{print $4}')
	mosquitto_sub -t "glp/0/17q2d9v/fb/con/test11/sts" > ${STS_PATH} &
	pids+=($!)
	mosquitto_pub -m '{"action":"delete"}' -t "glp/0/17q2d9v/rq/con/test11/do"
	parse_sts "${dcm_del_state}"
	result "sts"
	pub=("mosquitto_pub -m '{"action":"delete"}' -t '"glp/0/17q2d9v/rq/con/test11/do"'")
	result_logs "dcm_delete_test" ${LOG_DCM_DELETE}  ${start_time} "${pub}"
}


dcm_delete_test1
dcm_delete_test2
dcm_delete_test3

kill_process

