#!/bin/bash	

IOX_PATH="/home/unmesh/iox_test/"
source ${IOX_PATH}"common"
LOGGER_PATH=${IOX_PATH}"dio/din/logger"
STS_PATH=${IOX_PATH}"dio/din/sts"

invalid_port="The port asked for is not valid"

din_port_test1()
{
	subscribe_logger_event &	
	mosquitto_pub -m '{"di-val":{"value":{"type":"level","di-level":{"report-dur":1000,"detect-level":0,"pullup-cfg":true},"di-pulse":{"report-dur":10,"detect-level":0,"pullup-cfg":true},"di-frequency":{"report-dur":100,"detect-level":0,"pullup-cfg":true}},"monitor":{"rate":1500,"cat":"data","inFeedback":false,"report":"change","throttle":0,"threshold":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/di/1"
	parse_logger
}

din_port_test2()
{
	subscribe_logger_event &	
#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/di/2" > ${LOGGER_PATH} &
	mosquitto_pub -m '{"di-val":{"value":{"type":"level","di-level":{"report-dur":1000,"detect-level":0,"pullup-cfg":true},"di-pulse":{"report-dur":10,"detect-level":0,"pullup-cfg":true},"di-frequency":{"report-dur":100,"detect-level":0,"pullup-cfg":true}},"monitor":{"rate":1500,"cat":"data","inFeedback":false,"report":"change","throttle":0,"threshold":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/di/2"
	parse_logger

}

din_port_test3()
{
	subscribe_logger_event &	
#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/di/3" > ${LOGGER_PATH} &
	mosquitto_pub -m '{"di-val":{"value":{"type":"level","di-level":{"report-dur":1000,"detect-level":0,"pullup-cfg":true},"di-pulse":{"report-dur":10,"detect-level":0,"pullup-cfg":true},"di-frequency":{"report-dur":100,"detect-level":0,"pullup-cfg":true}},"monitor":{"rate":1500,"cat":"data","inFeedback":false,"report":"change","throttle":0,"threshold":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/di/3"
	parse_logger

}

din_port_test4()
{
	subscribe_logger_event &	
#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/di/4" > ${LOGGER_PATH} &
	mosquitto_pub -m '{"di-val":{"value":{"type":"level","di-level":{"report-dur":1000,"detect-level":0,"pullup-cfg":true},"di-pulse":{"report-dur":10,"detect-level":0,"pullup-cfg":true},"di-frequency":{"report-dur":100,"detect-level":0,"pullup-cfg":true}},"monitor":{"rate":1500,"cat":"data","inFeedback":false,"report":"change","throttle":0,"threshold":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/di/4"
	parse_logger

}

din_port_test5()
{
	subscribe_logger_event &	
#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/di/5" > ${LOGGER_PATH} &
	mosquitto_pub -m '{"di-val":{"value":{"type":"level","di-level":{"report-dur":1000,"detect-level":0,"pullup-cfg":true},"di-pulse":{"report-dur":10,"detect-level":0,"pullup-cfg":true},"di-frequency":{"report-dur":100,"detect-level":0,"pullup-cfg":true}},"monitor":{"rate":1500,"cat":"data","inFeedback":false,"report":"change","throttle":0,"threshold":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/di/5"
	parse_logger

}

din_port_test6()
{
	subscribe_logger_event &	
#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/di/6" > ${LOGGER_PATH} &
	mosquitto_pub -m '{"di-val":{"value":{"type":"level","di-level":{"report-dur":1000,"detect-level":0,"pullup-cfg":true},"di-pulse":{"report-dur":10,"detect-level":0,"pullup-cfg":true},"di-frequency":{"report-dur":100,"detect-level":0,"pullup-cfg":true}},"monitor":{"rate":1500,"cat":"data","inFeedback":false,"report":"change","throttle":0,"threshold":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/di/6"
	parse_logger

}

din_port_test7()
{
	subscribe_logger_event &	
#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/di/7" &
	mosquitto_pub -m '{"di-val":{"value":{"type":"level","di-level":{"report-dur":1000,"detect-level":0,"pullup-cfg":true},"di-pulse":{"report-dur":10,"detect-level":0,"pullup-cfg":true},"di-frequency":{"report-dur":100,"detect-level":0,"pullup-cfg":true}},"monitor":{"rate":1500,"cat":"data","inFeedback":false,"report":"change","throttle":0,"threshold":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/di/7"
	parse_logger

}

din_port_test8()
{
	subscribe_logger_event &	
#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/di/8" &
	mosquitto_pub -m '{"di-val":{"value":{"type":"level","di-level":{"report-dur":1000,"detect-level":0,"pullup-cfg":true},"di-pulse":{"report-dur":10,"detect-level":0,"pullup-cfg":true},"di-frequency":{"report-dur":100,"detect-level":0,"pullup-cfg":true}},"monitor":{"rate":1500,"cat":"data","inFeedback":false,"report":"change","throttle":0,"threshold":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/di/8"
	parse_logger

}

din_port_test9()
{
	echo -n "din_port_test"${test_num} | tee -a ${RESULT_LOG}
	((test_num++)) 
	start_time=$(date)
	echo -n " | "${start_time} | tee -a ${RESULT_LOG}
	subscribe_logger_event &	
#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/di/10" &
	mosquitto_pub -m '{"di-val":{"value":{"type":"level","di-level":{"report-dur":1000,"detect-level":0,"pullup-cfg":true},"di-pulse":{"report-dur":10,"detect-level":0,"pullup-cfg":true},"di-frequency":{"report-dur":100,"detect-level":0,"pullup-cfg":true}},"monitor":{"rate":1500,"cat":"data","inFeedback":false,"report":"change","throttle":0,"threshold":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/di/10"
	parse_logger "${invalid_port}"
	result "logger"
	end_time=$(date)
	echo -n " | "${end_time} | tee -a ${RESULT_LOG}
	echo "" | tee -a ${RESULT_LOG}
	echo "=============================================================================="
}

setup_time

din_port_test1
din_port_test2
din_port_test3
din_port_test4
din_port_test5
din_port_test6
din_port_test7
din_port_test8
din_port_test9

kill_process

