#!/bin/bash

source env_var.sh
source ${IOX_PATH}"/common.sh"
source ${IOX_PATH}"/iox.config"
source ${IOX_PATH}"/errors.sh"

LOG_EVENT_LOGGER=${IOX_PATH}"/dio/din/logger"
LOG_STS=${IOX_PATH}"/dio/din/sts"
LOG_DIN_DEEP=${IOX_PATH}"/dio/din/din_deep_log"

din_err_parse_json="Error in parsing json object"

din_deep_test1()
{
	start_time=$(date | awk '{print $4}')
	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '30' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${DIO_DEV_NAME}/if/dia/1/di-val/monitor/rate" 
	parse_logger "${din_err_parse_json}"
	result "logger"
	pub=("mosquitto_pub -m '30' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${DIO_DEV_NAME}/if/dia/1/di-val/monitor/rate"'")
	result_logs "din_deep_test" ${LOG_DIN_DEEP}  ${start_time} "${pub}"
}

din_deep_test2()
{
	start_time=$(date | awk '{print $4}')
	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '30' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${DIO_DEV_NAME}/if/di/1/di-vala/monitor/rate" 
	parse_logger
	result "logger"
	pub=("mosquitto_pub -m '30' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${DIO_DEV_NAME}/if/di/1/di-vala/monitor/rate"'")
	result_logs "din_deep_test" ${LOG_DIN_DEEP}  ${start_time} "${pub}"
}

din_deep_test3()
{
	start_time=$(date | awk '{print $4}')
	subscribe_logger_event &
	pids+=($!)
#	mosquitto_sub -t "glp/0/${SID}/fb/dev/${IOX_PROTOCOL}/${DIO_DEV_NAME}/if/di/1" > ${LOGGER_PATH} &
	mosquitto_pub -m '{"di-val":{"value":{"type":"frequency","di-level":{"report-dur":1000,"detect-level":0,"pullup-cfg":true},"di-pulse":{"report-dur":10,"detect-level":0,"pullup-cfg":true},"di-frequency":{"report-dur":100,"detect-level":0,"pullup-cfg":true}},"monitor":{"rate":15,"cat":"data","inFeedback":true,"report":"change","throttle":0,"threshold":10}}}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${DIO_DEV_NAME}/if/di/1"
	parse_logger
	result "logger"
	pub=("mosquitto_pub -m '{"di-val":{"value":{"type":"frequency","di-level":{"report-dur":1000,"detect-level":0,"pullup-cfg":true},"di-pulse":{"report-dur":10,"detect-level":0,"pullup-cfg":true},"di-frequency":{"report-dur":100,"detect-level":0,"pullup-cfg":true}},"monitor":{"rate":15,"cat":"data","inFeedback":true,"report":"change","throttle":0,"threshold":10}}}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${DIO_DEV_NAME}/if/di/1"'")
	result_logs "din_deep_test" ${LOG_DIN_DEEP}  ${start_time} "${pub}"
}

din_deep_test4()
{
	start_time=$(date | awk '{print $4}')
	subscribe_logger_event &
	pids+=($!)
#	mosquitto_sub -t "glp/0/${SID}/fb/dev/${IOX_PROTOCOL}/${DIO_DEV_NAME}/if/di/1" > ${LOGGER_PATH}  &
	mosquitto_pub -m '{"value":{"type":"level","di-level":{"report-dur":1000,"detect-level":0,"pullup-cfg":true},"di-pulse":{"report-dur":10,"detect-level":0,"pullup-cfg":true},"di-frequency":{"report-dur":100,"detect-level":0,"pullup-cfg":true}},"monitor":{"rate":100,"cat":"data","inFeedback":true,"report":"change","throttle":0,"threshold":10}}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${DIO_DEV_NAME}/if/di/1/di-val"
	parse_logger
	result "logger"
	pub=("mosquitto_pub -m '{"value":{"type":"level","di-level":{"report-dur":1000,"detect-level":0,"pullup-cfg":true},"di-pulse":{"report-dur":10,"detect-level":0,"pullup-cfg":true},"di-frequency":{"report-dur":100,"detect-level":0,"pullup-cfg":true}},"monitor":{"rate":100,"cat":"data","inFeedback":true,"report":"change","throttle":0,"threshold":10}}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${DIO_DEV_NAME}/if/di/1/di-val"'")
	result_logs "din_deep_test" ${LOG_DIN_DEEP}  ${start_time} "${pub}"
}

din_deep_test5()
{
	subscribe_logger_event &
#	mosquitto_sub -t "glp/0/${SID}/fb/dev/${IOX_PROTOCOL}/${DIO_DEV_NAME}/if/di/1" > ${LOGGER_PATH}  &
	mosquitto_pub -m '{"rate":50}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${DIO_DEV_NAME}/if/di/1/di-val/monitor"
	parse_logger
	result "logger"
	pub=("mosquitto_pub -m '{"rate":50}' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${DIO_DEV_NAME}/if/di/1/di-val/monitor"'")
	result_logs "din_deep_test" ${LOG_DIN_DEEP}  ${start_time} "${pub}"
}

din_deep_test6()
{
	subscribe_logger_event &
#	mosquitto_sub -t "glp/0/${SID}/fb/dev/${IOX_PROTOCOL}/${DIO_DEV_NAME}/if/di/1" > ${LOGGER_PATH}  &
	mosquitto_pub -m '30' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${DIO_DEV_NAME}/if/di/1/di-val/monitor/rate"
	parse_logger
	result "logger"
	pub=("mosquitto_pub -m '30' -t '"glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${DIO_DEV_NAME}/if/di/1/di-val/monitor/rate"'")
	result_logs "din_deep_test" ${LOG_DIN_DEEP}  ${start_time} "${pub}"
}


din_deep_test1
din_deep_test2
din_deep_test3
din_deep_test4
din_deep_test5
din_deep_test6

kill_process

