#!/bin/bash

LOGGER_PATH="/home/unmesh/iox_test/dio/din/logger"

kill_process()
{
    pkill mosquitto_sub
    if [[ $? -eq 0 ]];
    then
        echo "mosquitto_sub process killed"
    else
        echo "failed to kill mosquitto_sub process"
    fi
    rm ${LOGGER_PATH}
}

parse_logger()
{
	sleep 5
	if [[ -s ${LOGGER_PATH} ]];
	then 
		out=$(grep 'utc' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 -B4 -A1 "regex" ${LOGGER_PATH})
		parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
		echo "parse : "${parse}
	fi
}



din_deep_test1()
{

	echo "test1 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '30' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/dia/1/di-val/monitor/rate" 

}

din_deep_test2()
{

	echo "test2 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '30' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/di/1/di-vala/monitor/rate" 

}

din_deep_test3()
{

	echo "test3 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/di/1" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"di-val":{"value":{"type":"frequency","di-level":{"report-dur":1000,"detect-level":0,"pullup-cfg":true},"di-pulse":{"report-dur":10,"detect-level":0,"pullup-cfg":true},"di-frequency":{"report-dur":100,"detect-level":0,"pullup-cfg":true}},"monitor":{"rate":15,"cat":"data","inFeedback":true,"report":"change","throttle":0,"threshold":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/di/1"

}

din_deep_test4()
{

	echo "test4 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
#	mosquitto_sub -t "glp/0/17q3kc1/fb/dev/iox/dio/if/di/1" >> ${LOGGER_PATH}  &
	mosquitto_pub -m '{"value":{"type":"level","di-level":{"report-dur":1000,"detect-level":0,"pullup-cfg":true},"di-pulse":{"report-dur":10,"detect-level":0,"pullup-cfg":true},"di-frequency":{"report-dur":100,"detect-level":0,"pullup-cfg":true}},"monitor":{"rate":100,"cat":"data","inFeedback":true,"report":"change","throttle":0,"threshold":10}}' -t "glp/0/17q3kc1/rq/dev/iox/dio/if/di/1/di-val"

}

din_deep_test5()
{

	echo "test5 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
#	mosquitto_sub -t "glp/0/17q3kc1/fb/dev/iox/dio/if/di/1" >> ${LOGGER_PATH}  &
	mosquitto_pub -m '{"rate":50}' -t "glp/0/17q3kc1/rq/dev/iox/dio/if/di/1/di-val/monitor"

}

din_deep_test6()
{

	echo "test6 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
#	mosquitto_sub -t "glp/0/17q3kc1/fb/dev/iox/dio/if/di/1" >> ${LOGGER_PATH}  &
	mosquitto_pub -m '30' -t "glp/0/17q3kc1/rq/dev/iox/dio/if/di/1/di-val/monitor/rate"

}

din_deep_test1
din_deep_test2
din_deep_test3
din_deep_test4
din_deep_test5
din_deep_test6

kill_process
