#!/bin/bash

source env_var.sh
source ${IOX_PATH}"/common.sh"
source ${IOX_PATH}"/info_file.sh"
source ${IOX_PATH}"/errors.sh"


din_get_test1()
{

	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox/dio/if/di/1/di-val"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"

}

din_get_test2()
{

	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox/dio/if/di/1/di-val"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"

}

din_get_test3()
{

	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox/dioaww/if/di/1/di-val"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"

}

din_get_test4()
{

	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox/dio/if/di/10/di-val"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"

}

din_get_test5()
{

	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox/dio/if/di/1/di-valasd"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"

}

din_get_test6()
{

	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox/dio/if/di/1/di-val","dev/iox/dio/if/di/2/di-val"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"

}

din_get_test1
din_get_test2
din_get_test3
din_get_test4
din_get_test5
din_get_test6

sleep 10

kill_process

