#!/bin/bash

source env_var.sh
source ${IOX_PATH}"/iox.config"
source ${IOX_PATH}"/common.sh"
source ${IOX_PATH}"/info_file.sh"
source ${IOX_PATH}"/errors.sh"

OUT=${IOX_PATH}"/dio/din/out"

subscribe()
{
	mosquitto_sub -t "my/responses/di/1/input" > ${OUT}	
}

parse_out()
{
    sleep 5
    if [[ -s ${OUT} ]];
    then
		if [[ ${1} != "corr" ]];
		then
     		parse=$(cat ${OUT} | python -c 'import sys, json; a=json.load(sys.stdin)["result"];print a[0]["error"]')   
	 		if [[ ${parse} == ${1} ]];
        	then
            	RESULT="PASS"
        	else
            	RESULT="FAIL"
        	fi 
   		else
			parse=$(cat ${OUT} | python -c 'import sys, json; print json.load(sys.stdin)["corr"]')
			if [[ ${parse} == "abcd" ]];
			then
				RESULT="PASS"
			else
				RESULT="FAIL"
			fi
	 	fi
        rm ${OUT}
	else
        RESULT="EMPTY"
    fi
}

din_get_test1()
{
	start_time=$(date | awk '{print $4}')
	subscribe &
 	pids+=($!)
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses/di/1/input","item":["dev/'${IOX_PROTOCOL}'/'${DIO_DEV_NAME}'/if/di/1/input"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"
	parse_out "corr"
	end_time=$(date | awk '{print $4}')
    exec_time=$(execution_time ${start_time} ${end_time})
    echo "din_device_test1 | RESULT : ${RESULT} ${exec_time}"
    unset RESULT
}

din_get_test2()
{

	start_time=$(date | awk '{print $4}')
	subscribe &
 	pids+=($!)
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses/di/1/input","item":["dev/'${IOX_PROTOCOL}'2ee/'${DIO_DEV_NAME}'/if/di/1/input"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"
	sleep 10
	parse_out "No get response received for the datapoint dev/${IOX_PROTOCOL}2ee/${DIO_DEV_NAME}/if/di/1/input"
	end_time=$(date | awk '{print $4}')
    exec_time=$(execution_time ${start_time} ${end_time})
    echo "din_device_test2 | RESULT : ${RESULT} ${exec_time}"
    unset RESULT
}

din_get_test3()
{

	start_time=$(date | awk '{print $4}')
	subscribe &
 	pids+=($!)
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses/di/1/input","item":["dev/'${IOX_PROTOCOL}'/'${DIO_DEV_NAME}'aww/if/di/1/input"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"
	parse_out "datapoint not found"
	end_time=$(date | awk '{print $4}')
    exec_time=$(execution_time ${start_time} ${end_time})
    echo "din_device_test3 | RESULT : ${RESULT} ${exec_time}"
    unset RESULT
}

din_get_test4()
{

	start_time=$(date | awk '{print $4}')
	subscribe &
 	pids+=($!)
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses/di/1/input","item":["dev/'${IOX_PROTOCOL}'/'${DIO_DEV_NAME}'/if/di/1dfd/input"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"
	parse_out "datapoint not found"
	end_time=$(date | awk '{print $4}')
    exec_time=$(execution_time ${start_time} ${end_time})
    echo "din_device_test4 | RESULT : ${RESULT} ${exec_time}"
    unset RESULT
}

din_get_test5()
{

	start_time=$(date | awk '{print $4}')
	subscribe &
 	pids+=($!)
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses/di/1/input","item":["dev/'${IOX_PROTOCOL}'/'${DIO_DEV_NAME}'/if/di/1/inputasd"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"
	parse_out "datapoint not found"
	end_time=$(date | awk '{print $4}')
    exec_time=$(execution_time ${start_time} ${end_time})
    echo "din_device_test5 | RESULT : ${RESULT} ${exec_time}"
    unset RESULT
}

din_get_test6()
{
	start_time=$(date | awk '{print $4}')
	subscribe &
 	pids+=($!)
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses/di/1/input","item":["dev/'${IOX_PROTOCOL}'/'${DIO_DEV_NAME}'/if/di/1/input","dev/'${IOX_PROTOCOL}'/'${DIO_DEV_NAME}'/if/di/2/input"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"
	parse_out "corr"
	end_time=$(date | awk '{print $4}')
    exec_time=$(execution_time ${start_time} ${end_time})
    echo "din_device_test6 | RESULT : ${RESULT} ${exec_time}"
    unset RESULT
}

#din_get_test1
din_get_test2
#din_get_test3
#din_get_test4
#din_get_test5
#din_get_test6

sleep 10

kill_process

