#!/bin/bash

IOX_PATH="/home/unmesh/iox_test/"
source ${IOX_PATH}"common"
LOGGER_PATH=${IOX_PATH}"dio/din/logger"

wrong_config_level="Wrong configuration for level"
wrong_config_pulse="Wrong configuration for Pulse output"
wrong_config_freq="Wrong configuration for Frequency output"

din_mode_test1()
{  
  	subscribe_logger_event &
#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/di/1" &
	mosquitto_pub -m '{"di-val":{"value":{"type":"level","di-level":{"report-dur":1000,"detect-level":0,"pullup-cfg":true},"di-pulse":{"report-dur":10,"detect-level":0,"pullup-cfg":true},"di-frequency":{"report-dur":100,"detect-level":0,"pullup-cfg":true}},"monitor":{"rate":1500,"cat":"data","inFeedback":true,"report":"change","throttle":0,"threshold":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/di/1"
	parse_logger

}

din_mode_test2()
{

  	subscribe_logger_event &
#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/relay/2" &
	mosquitto_pub -m '{"do-val":{"value":{"type":"level","level":false,"frequency":0,"pulse":0,"pwm":{"frequency":0,"duty-cycle":0}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/1"
	parse_logger

}

din_mode_test3()
{

  	subscribe_logger_event &
	mosquitto_pub -m '{"do-val":{"value":{"type":"level","level":"true","frequency":0,"pulse":0,"pwm":{"frequency":20000,"duty-cycle":90}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/1"
	parse_logger "${wrong_config_level}"

}

din_mode_test4()
{

  	subscribe_logger_event &
#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/di/1" &
	mosquitto_pub -m '{"di-val":{"value":{"type":"pulse","di-level":{"report-dur":1000,"detect-level":0,"pullup-cfg":true},"di-pulse":{"report-dur":10,"detect-level":0,"pullup-cfg":true},"di-frequency":{"report-dur":100,"detect-level":0,"pullup-cfg":true}},"monitor":{"rate":15,"cat":"data","inFeedback":true,"report":"change","throttle":0,"threshold":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/1"
	parse_logger

}

din_mode_test5()
{

  	subscribe_logger_event &
	mosquitto_pub -m '{"do-val":{"value":{"type":"pulse","level":true,"frequency":0,"pulse":"test","pwm":{"frequency":20000,"duty-cycle":90}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/1"
	parse_logger "${wrong_config_pulse}"
}

din_mode_test6()
{

  	subscribe_logger_event &
#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/di/1" &
	mosquitto_pub -m '{"di-val":{"value":{"type":"frequency","di-level":{"report-dur":1000,"detect-level":0,"pullup-cfg":true},"di-pulse":{"report-dur":10,"detect-level":0,"pullup-cfg":true},"di-frequency":{"report-dur":100,"detect-level":0,"pullup-cfg":true}},"monitor":{"rate":15,"cat":"data","inFeedback":true,"report":"change","throttle":0,"threshold":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/di/1"
	parse_logger

}

din_mode_test7()
{
  	subscribe_logger_event &
	mosquitto_pub -m '{"do-val":{"value":{"type":"frequency","level":true,"frequency":"test","pulse":0,"pwm":{"frequency":20000,"duty-cycle":90}}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/do/1"
	parse_logger "${wrong_config_freq}"
}

din_mode_test1
din_mode_test2
din_mode_test3
din_mode_test4
din_mode_test5
din_mode_test6
din_mode_test7

kill_process

