#!/bin/bash	

LOGGER_PATH="/home/unmesh/iox_test/dio/din/logger"

kill_process()
{
    pkill mosquitto_sub
    if [[ $? -eq 0 ]];
    then
        echo "mosquitto_sub process killed"
    else
        echo "failed to kill mosquitto_sub process"
    fi
    rm ${LOGGER_PATH}
}

parse_logger()
{
	sleep 5
	if [[ -s ${LOGGER_PATH} ]];
	then 
		out=$(grep 'utc' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 -B4 -A1 "regex" ${LOGGER_PATH})
		parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
		echo "parse : "${parse}
	fi
}

din_port_test1()
{

	echo "test1 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"di-val":{"value":{"type":"level","di-level":{"report-dur":1000,"detect-level":0,"pullup-cfg":true},"di-pulse":{"report-dur":10,"detect-level":0,"pullup-cfg":true},"di-frequency":{"report-dur":100,"detect-level":0,"pullup-cfg":true}},"monitor":{"rate":1500,"cat":"data","inFeedback":false,"report":"change","throttle":0,"threshold":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/di/1"
	parse_logger
}

din_port_test2()
{


	echo "test2 : " > ${LOGGER_PATH}
#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/di/2" >> ${LOGGER_PATH} &
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"di-val":{"value":{"type":"level","di-level":{"report-dur":1000,"detect-level":0,"pullup-cfg":true},"di-pulse":{"report-dur":10,"detect-level":0,"pullup-cfg":true},"di-frequency":{"report-dur":100,"detect-level":0,"pullup-cfg":true}},"monitor":{"rate":1500,"cat":"data","inFeedback":false,"report":"change","throttle":0,"threshold":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/di/2"
	parse_logger

}

din_port_test3()
{

	echo "test3 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/di/3" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"di-val":{"value":{"type":"level","di-level":{"report-dur":1000,"detect-level":0,"pullup-cfg":true},"di-pulse":{"report-dur":10,"detect-level":0,"pullup-cfg":true},"di-frequency":{"report-dur":100,"detect-level":0,"pullup-cfg":true}},"monitor":{"rate":1500,"cat":"data","inFeedback":false,"report":"change","throttle":0,"threshold":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/di/3"
	parse_logger

}

din_port_test4()
{

	echo "test4 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/di/4" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"di-val":{"value":{"type":"level","di-level":{"report-dur":1000,"detect-level":0,"pullup-cfg":true},"di-pulse":{"report-dur":10,"detect-level":0,"pullup-cfg":true},"di-frequency":{"report-dur":100,"detect-level":0,"pullup-cfg":true}},"monitor":{"rate":1500,"cat":"data","inFeedback":false,"report":"change","throttle":0,"threshold":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/di/4"
	parse_logger

}

din_port_test5()
{
	
	echo "test5 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/di/5" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"di-val":{"value":{"type":"level","di-level":{"report-dur":1000,"detect-level":0,"pullup-cfg":true},"di-pulse":{"report-dur":10,"detect-level":0,"pullup-cfg":true},"di-frequency":{"report-dur":100,"detect-level":0,"pullup-cfg":true}},"monitor":{"rate":1500,"cat":"data","inFeedback":false,"report":"change","throttle":0,"threshold":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/di/5"
	parse_logger

}

din_port_test6()
{

	echo "test6 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/di/6" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"di-val":{"value":{"type":"level","di-level":{"report-dur":1000,"detect-level":0,"pullup-cfg":true},"di-pulse":{"report-dur":10,"detect-level":0,"pullup-cfg":true},"di-frequency":{"report-dur":100,"detect-level":0,"pullup-cfg":true}},"monitor":{"rate":1500,"cat":"data","inFeedback":false,"report":"change","throttle":0,"threshold":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/di/6"
	parse_logger

}

din_port_test7()
{

	echo "test7 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/di/7" &
	mosquitto_pub -m '{"di-val":{"value":{"type":"level","di-level":{"report-dur":1000,"detect-level":0,"pullup-cfg":true},"di-pulse":{"report-dur":10,"detect-level":0,"pullup-cfg":true},"di-frequency":{"report-dur":100,"detect-level":0,"pullup-cfg":true}},"monitor":{"rate":1500,"cat":"data","inFeedback":false,"report":"change","throttle":0,"threshold":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/di/7"
	parse_logger

}

din_port_test8()
{

	echo "test8 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/di/8" &
	mosquitto_pub -m '{"di-val":{"value":{"type":"level","di-level":{"report-dur":1000,"detect-level":0,"pullup-cfg":true},"di-pulse":{"report-dur":10,"detect-level":0,"pullup-cfg":true},"di-frequency":{"report-dur":100,"detect-level":0,"pullup-cfg":true}},"monitor":{"rate":1500,"cat":"data","inFeedback":false,"report":"change","throttle":0,"threshold":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/di/8"
	parse_logger

}

din_port_test9()
{

	echo "test9 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
#	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/di/10" &
	mosquitto_pub -m '{"di-val":{"value":{"type":"level","di-level":{"report-dur":1000,"detect-level":0,"pullup-cfg":true},"di-pulse":{"report-dur":10,"detect-level":0,"pullup-cfg":true},"di-frequency":{"report-dur":100,"detect-level":0,"pullup-cfg":true}},"monitor":{"rate":1500,"cat":"data","inFeedback":false,"report":"change","throttle":0,"threshold":10}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/di/10"
	parse_logger

}

din_port_test1
din_port_test2
din_port_test3
din_port_test4
din_port_test5
din_port_test6
din_port_test7
din_port_test8
din_port_test9

kill_process
