#!/bin/bash

source env_var.sh
source ${IOX_PATH}"/common.sh"
source ${IOX_PATH}"/iox.config"
source ${IOX_PATH}"/errors.sh"

LOG_EVENT_LOGGER=${IOX_PATH}"/dio/relay/logger"
LOG_STS=${IOX_PATH}"/dio/relay/sts"
LOG_RELAY_DEEP=${IOX_PATH}"/dio/relay/relay_deep_log"


relay_deep_test1()
{
	start_time=$(date | awk '{print $4}')
  	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m 'true' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/relay/if/relay/1/relay-val/value/level12"
	parse_logger
	result "logger"
	result_logs "relay_deep_test" ${LOG_RELAY_DEEP}  ${start_time} "${pub}"
}

relay_deep_test2()
{
	start_time=$(date | awk '{print $4}')
  	subscribe_logger_event &
	pids+=($!)
#	mosquitto_sub -t "glp/0/${SID}/fb/dev/${IOX_PROTOCOL}/relay/if/relay/1" &
	mosquitto_pub -m 'true' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/relay/if/relay/1/relay-val/value/level"
	parse_logger
	result "logger"
	result_logs "relay_deep_test" ${LOG_RELAY_DEEP}  ${start_time} "${pub}"
}


relay_deep_test1
relay_deep_test2

sleep 10
kill_process

