#!/bin/bash

source env_var.sh
source ${IOX_PATH}"/common.sh"
source ${IOX_PATH}"/iox.config"
source ${IOX_PATH}"/errors.sh"

LOG_EVENT_LOGGER=${IOX_PATH}"/dio/relay/logger"
LOG_STS=${IOX_PATH}"/dio/relay/sts"
LOG_RELAY_DEVICE=${IOX_PATH}"/dio/relay/relay_device_log"


relay_device_test1()
{
	start_time=$(date | awk '{print $4}')
  	subscribe_logger_event &
	pids+=($!)
	mosquitto_pub -m '{"relay-val":{"value":{"level":true}}}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${METER_DEV_NAME}/if/relay/1"
	parse_logger
	result "logger"
	result_logs "relay_device_test" ${LOG_RELAY_DEVICE}  ${start_time} "${pub}"
}

relay_device_test2()
{
	start_time=$(date | awk '{print $4}')
  	subscribe_logger_event &
	pids+=($!)
#	mosquitto_sub -t "glp/0/${SID}/fb/dev/${IOX_PROTOCOL}/dio/if/relay/1" &
	mosquitto_pub -m '{"relay-val":{"value":{"level":true}}}' -t "glp/0/${SID}/rq/dev/${IOX_PROTOCOL}/${DIO_DEV_NAME}/if/relay/1"
	parse_logger
	result "logger"
	result_logs "relay_device_test" ${LOG_RELAY_DEVICE}  ${start_time} "${pub}"
}


relay_device_test1
relay_device_test2

kill_process

