#!/bin/bash

kill_process()
{
    pkill mosquitto_sub
    if [[ $? -eq 0 ]];
    then
        echo "mosquitto_sub process killed"
    else
        echo "failed to kill mosquitto_sub process"
    fi
}



relay_valueObj_test1()
{
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/relay/2" &
	mosquitto_pub -m '{"relay-val":{"value":{"level":false}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/1"
}

relay_valueObj_test1

sleep 10

kill_process
