#!/bin/bash

LOGGER_PATH="/home/unmesh/iox_test/dio/relay/logger"

kill_process()
{
	pkill mosquitto_sub 
	if [[ $? -eq 1 ]];
	then
		echo "failed to kill mosquitto_sub process"
	fi
}

parse_logger()
{
	sleep 5
	if [[ -s ${LOGGER_PATH} ]];
	then 
		out=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 "regex" ${LOGGER_PATH})
		out_time=$(awk -F "," '/utc/{print $4}' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | awk '{print $2}')
		if [[ ${last_out_time} == ${out_time} ]];
		then
			echo "NO NEW MESSAGE FROM LOGGER"
		else
			parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
			if [[ ${parse} == ${1} ]];
			then
				LOGGER_RESULT="PASS"
			else
				LOGGER_RESULT="FAIL"
			fi
			last_out_time=${out_time}
		fi
	fi
	rm ${LOGGER_PATH}
}

subscribe_logger_event()
{
    mosquitto_sub -t "glp/0/./=logger/event" > ${LOGGER_PATH}
}


relay_port_test1()
{
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/relay/1" &
	mosquitto_pub -m '{"relay-val":{"value":{"level":true}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/1"
}

relay_port_test2()
{
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/relay/2" &
	mosquitto_pub -m '{"relay-val":{"value":{"level":true}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/2" 
}

relay_port_test3()
{
	subscribe_logger_event &
	mosquitto_pub -m '{"relay-val":{"value":{"level":true}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/3"
	parse_logger
}


relay_port_test1
relay_port_test2
relay_port_test3

kill_process

