#!/bin/bash

LOGGER_PATH="/home/unmesh/iox_test/dio/relay/logger"

kill_process()
{
    pkill mosquitto_sub
    if [[ $? -eq 0 ]];
    then
        echo "mosquitto_sub process killed"
    else
        echo "failed to kill mosquitto_sub process"
    fi
    rm ${LOGGER_PATH}
}

parse_logger()
{
	sleep 5
	if [[ -s ${LOGGER_PATH} ]];
	then 
		out=$(grep 'utc' ${LOGGER_PATH} | grep -oP '[[:digit:]].*(?= [[:space:]]*UTC.*)' | sort -k1,2 -ur | head -n1 | xargs -Iregex grep -m1 -B4 -A1 "regex" ${LOGGER_PATH})
		parse=$(echo ${out} | python -c 'import sys, json; print json.load(sys.stdin)["message"]')
		echo "parse : "${parse}
	fi
}

relay_device_test1()
{
	echo "test1 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_pub -m '{"relay-val":{"value":{"level":true}}}' -t "glp/0/17q2d9v/rq/dev/iox/meter/if/relay/1"
	parse_logger
}

relay_device_test2()
{
	echo "test2 : " > ${LOGGER_PATH}
	mosquitto_sub -t "glp/0/./=logger/event" >> ${LOGGER_PATH} &
	mosquitto_sub -t "glp/0/17q2d9v/fb/dev/iox/dio/if/relay/1" &
	mosquitto_pub -m '{"relay-val":{"value":{"level":true}}}' -t "glp/0/17q2d9v/rq/dev/iox/dio/if/relay/1"
	parse_logger
}

relay_device_test1
relay_device_test2

kill_process
