#!/bin/bash

kill_process()
{
    pkill mosquitto_sub
    if [[ $? -eq 0 ]];
    then
        echo "mosquitto_sub process killed"
    else
        echo "failed to kill mosquitto_sub process"
    fi
}

relay_get_test1()
{
	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox/dio/if/relay/1/relay-val"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"
}

relay_get_test2()
{
	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox1234/dio/if/relay/1/relay-val"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"
}

relay_get_test3()
{
	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox/dio12/if/relay/1/relay-val"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"
}

relay_get_test4()
{
	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox/dio/if/relay/5/relay-val"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"
}

relay_get_test5()
{
	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox/dio/if/relay/1/relay-val12"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"
}

relay_get_test6()
{
	
	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox/dio/if/relay/1/relay-val","dev/iox/dio/if/relay/2/relay-val"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"
}

relay_get_test1
relay_get_test2
relay_get_test3
relay_get_test4
relay_get_test5
relay_get_test6

sleep 10
kill_process
