#!/bin/bash

source env_var.sh
source ${IOX_PATH}"/common.sh"
source ${IOX_PATH}"/iox.config"
source ${IOX_PATH}"/errors.sh"

relay_get_test1()
{
	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox/dio/if/relay/1/relay-val"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"
}

relay_get_test2()
{
	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox/dio/if/relay/1/relay-val"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"
}

relay_get_test3()
{
	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox/dio12/if/relay/1/relay-val"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"
}

relay_get_test4()
{
	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox/dio/if/relay/5/relay-val"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"
}

relay_get_test5()
{
	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox/dio/if/relay/1/relay-val12"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"
}

relay_get_test6()
{
	
	mosquitto_sub -t "my/responses" &
	mosquitto_pub -m '{"corr":"abcd","response":"my/responses","item":["dev/iox/dio/if/relay/1/relay-val","dev/iox/dio/if/relay/2/relay-val"],"maxAge":1,"timeout":10}' -t "glp/0/./=get/dp/request"
}

relay_get_test1
relay_get_test2
relay_get_test3
relay_get_test4
relay_get_test5
relay_get_test6

sleep 10
kill_process

